### ISSUE TITLE
request.uri.port is nil on ubuntu 

### ISSUE THREAD

**Issue by truemetal** [vapor/vapor#929] opened 2017-03-25 22:53 UTC
That pretty much tells it. When I print `"request port \(request.uri.port)"` from a middleware the output is nil. At the same time e.g. `request.uri.path` or `request.uri.host` do contain data.

That happens on `ubuntu 16.04.2`, while works beautifully on `mac os`.

**Comment by tanner0101** [comment] 2017-03-27 06:12
@truemetal could you do `print(request)` and provide us with the output? 

also may be worth moving this issue to https://github.com/vapor/engine where the code for request and uri resides.

**Comment by truemetal** [comment] 2017-03-27 09:31
@tanner0101 

```
Request
- GET /hi/there HTTP/1.1
- Headers:
	Accept: */*
	Host: mobile-backend.ddns.net
	User-Agent: curl/7.51.0
- Body:
```

**Comment by tanner0101** [comment] 2017-05-11 21:04
strange a port is showing up on macOS, but from the request you supplied, this seems like expected behavior. (no port is supplied in the URI, it's just a path). i'd recommend using ` ?? 80` or using the scheme to determine which port to use if you need it.

**Closed by tanner0101** 2017-05-11 21:04 UTC
Labels: bug

**Comment by truemetal** [comment] 2017-05-12 14:29
@tanner0101 my use case was to check whether request came to port 80 or port 433, and that was not possible `request.uri.port`

While indeed that works on `macOS`

**Comment by tanner0101** [comment] 2017-05-12 15:18
Something about the browser/request must be different if a port is showing up there and not on Linux.

**Comment by ckd** [comment] 2017-05-12 19:48
So it looks like there's some iffy stuff in the way scheme is determined that I haven't had a chance to really take a look at, which results in a key that isn't in the defaultPorts array.

@truemetal Are you using nginx? If so, that compounds the problem because it seems as though nginx drops the port from $http_host if the port is 80. The easiest thing to do then would be to append $http_port to the host header in nginx. You'd only want to do that if it's on port 80, however... for other ports $http_port would get appended twice.
