### ISSUE TITLE
Add Ability to Define a Date Format for URLEncodedFormEncoder and URLEncodedFormDecoder

### ISSUE THREAD

**Issue by thecheatah** [vapor/vapor#2272] opened 2020-03-29 04:53 UTC
Created pull request https://github.com/vapor/vapor/pull/2273

### Steps to reproduce

Currently, the URL Coders code and decode to Unix Timestamp. I would like to be able to override  code/decode to support ISO 8601 and custom date formats.

[ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) Supports all of the following date formats (and more):
* 2020-03-29
* 2020-03-29T14:25:05+00:00
* 2020-03-29T14:25:05Z

### Expected behavior

Modify URLEncodedFormDecoder.Configuration to take an array of enum values DateFormat where decoding will be tried with the date formats provided in the array. Defaults to decoding as Unix Timestamp and if that doesn't work ISO8601 (`[.timeIntervalSince1970, .iso8601]`).

Where `URLEncodedFormDecoder.Configuration.DateFormat` is
```swift
        /// Supported date formats
        public enum DateFormat {
            /// Seconds since 1 January 1970 00:00:00 UTC
            case unixTimestamp
            /// ISO 8601 formatted date
            case iso8601
            /// Using custom callback
            case custom((Decoder) throws -> Date)
        }
```
Modify URLEncodedFormEncoder.Configuration to take in enum value DateFormat. Defaults to Unix Timestamp (`.unixTimestamp`)

Where `URLEncodedFormEncoder.Configuration.DateFormat` is
```swift
        /// Supported date formats
        public enum DateFormat {
            /// Seconds since 1 January 1970 00:00:00 UTC
            case unixTimestamp
            /// ISO 8601 formatted date
            case iso8601
            /// Using custom callback
            case custom((Date, Encoder) throws -> Void)
        }
```
### Actual behavior

No ability to override date formatting.

### Environment

* Vapor Framework version: 4
* Vapor Toolbox version:
* OS version: Linux

**Comment by thecheatah** [comment] 2020-03-29 04:57
Seems like Swift on Linux should support [ISO8601DateFormatter](https://github.com/apple/swift-corelibs-foundation/blob/master/Sources/Foundation/ISO8601DateFormatter.swift). ISO8601DateFormatter inherits from Formatter instead of DateFormatter. Not sure why

**Comment by Joannis** [comment] 2020-03-30 12:29
Can this be added post-release/without breaking API? I think so, in which case adding this with the current method as default would be preferred for me.

**Comment by thecheatah** [comment] 2020-03-30 13:46
@Joannis Thanks for taking a look. We can default it to `timeIntervalSinceReferenceDate`, but it didn't make sense for it to be the default as it's Apple specific.

I have a feeling that not a lot of people have tried to Encode/Decode to date from the URLEncodedForm, otherwise someone would have raised it as a bug.

I can default it to `timeIntervalSinceReferenceDate` if considering the above, we are OK with defaulting date encoding/decoding to something non-standard. Vapor 4 implementations will go live expecting Apple's `timeIntervalSinceReferenceDate`

**Comment by thecheatah** [comment] 2020-03-30 14:28
Default to `timeIntervalSinceReferenceDate`

**Comment by tanner0101** [comment] 2020-04-02 17:34
Duplicate of https://github.com/vapor/vapor/issues/2133

**Closed by tanner0101** 2020-04-02 17:34 UTC
Labels: enhancement
