### ISSUE TITLE
Bug: Unable to use models inherited from parent class with type safe routing

### ISSUE THREAD

**Issue by kgn** [vapor/vapor#809] opened 2017-02-01 01:58 UTC
I have two models `Employer` and `Employee` who both inherit from a `BusinessModel` parent class with properties that I want all my models to have like `created_at` and `updated_at`.

I've run into an issue with this setup where I cannot use type safe routing, i.e. `drop.get("employer", Employer.self)`.

I dug into this with help from `0xtim` on the Slack `#help` channel. What we found was that:

In [this method of `TypeSafeRouting/Generated.swift`](https://github.com/vapor/routing/blob/master/Sources/TypeSafeRouting/Generated.swift#L440) `W0` is `Employer`. `try W0(from: vw0)` runs [`Model.init(from string: String)` in `Vapor/Fluent/Model.swift`](https://github.com/vapor/vapor/blob/master/Sources/Vapor/Fluent/Model.swift#L29), now `Self` is `BusinessModel` so the model look up in the database fails.

So between these two steps the model class is upcasted causing `find` to fail.

**Comment by kgn** [comment] 2017-02-02 06:38
I made this simple example to illustrate the issue. Route `/dogA/1` returns a 404 while route `/dogB/1` return the correct model.

``` swift
import Vapor
import Fluent
import VaporSQLite
import Foundation

public class Animal: Model {
    public var id: Node?
    public var exists = false
    
    public var name: String
    
    public init(name: String) {
        self.name = name
    }
    
    public required init(node: Node, in context: Context) throws {
        self.id = try node.extract("id")
        self.name = try node.extract("name")
    }
    
    public func makeNode(context: Context) throws -> Node {
        return try Node(node: [
            "id": self.id,
            "name": self.name
        ])
    }
    
    class func prepare(model: Schema.Creator) throws { }
    
    public static func prepare(_ database: Database) throws {
        try database.create(self.entity) { model in
            model.id()
            model.string("name")
            
            try self.prepare(model: model)
        }
    }
    
    public static func revert(_ database: Database) throws {
        try database.delete(self.entity)
    }
    
}

final class Dog: Animal {
    var breed: String?
    
    public init(breed: String) {
        self.breed = breed
        super.init(name: "Dog")
    }
    
    public required init(node: Node, in context: Context) throws {
        self.breed = try node.extract("breed")
        try super.init(node: node, in: context)
    }
    
    public override func makeNode(context: Context) throws -> Node {
        var node = try super.makeNode(context: context)
        node["breed"] = self.breed?.makeNode()
        return node
    }
    
    override class func prepare(model: Schema.Creator) throws {
        model.string("breed")
    }
    
}


let drop = Droplet()

try drop.addProvider(VaporSQLite.Provider.self)
drop.preparations.append(Dog.self)

// Make a dog
drop.post("dog") { request in
    var dog = Dog(breed: "Golden Retriever")
    try dog.save()
    return dog
}

// Doesn't work

drop.get("dogA", Dog.self) { request, dog in
    return dog
}

// Works

drop.get("dogB", ":id") { request in
    guard let id = request.parameters["id"] else { throw Abort.badRequest }
    guard let dog = try Dog.find(id) else { throw Abort.badRequest }
    return dog
}

drop.run()
```

**Comment by tannernelson** [comment] 2017-02-02 09:07
Thanks for the detailed issue. 

```swift
func get<W0: StringInitializable>(_ p0: String, _ w0: W0.Type, handler: @escaping (Request, W0) throws -> ResponseRepresentable)
```

This is the method signature for that function. Since we're using a generic here it should work. My guess is that this is a bug or a limitation in the Swift generic system right now. 

Would you want to copy/paste this into a bug report on bugs.swift.org? If not, I can.

**Comment by kgn** [comment] 2017-02-02 16:08
@tannernelson it might be better if you do it as you likely can explain the bug with the generic system better ;) If you need anymore information from me please let me know!

**Comment by LoganWright** [comment] 2017-02-03 13:04
@kgn @tannernelson I'm not sure how to report this, but I'm almost certain it's a Swift bug. I'm unable to recreate it in a way separate from Vapor.

I did however gain some more info that leads me to believe this is a Swift issue. If I add:


```swift
            print("type: \(W0.self)")
            let ew0 = try W0(from: vw0)
```

into the function from here:

```
public func get<W0: StringInitializable>(_ p0: String, _ w0: W0.Type, handler: @escaping (Request, W0) throws -> ResponseRepresentable) {
```

Then it will log

> type Dog

However, if I add a log here as well:

```swift
extension Model {
    public init?(from string: String) throws {
        print("init type: \(Self.self)")
        if let model = try Self.find(string) {
            self = model
        } else {
            return nil
        }
    }
}
```

Then it will log

> init type Animal

Even though it's the next call.

Unfortunately, to do the init magic we use, it needs to be in a protocol, so I don't think there's anything we can do except work around it until we find a way to reproduce it in a way that's reportable.

**Comment by tannernelson** [comment] 2017-02-03 13:52
Probably has something to do with crossing into another module.

**Comment by JuanjoArreola** [comment] 2017-03-24 18:01
I think is the same problem reported here: https://bugs.swift.org/browse/SR-3862

**Comment by tanner0101** [comment] 2017-04-27 11:34
Closing the issue here in favor of the issue on Swift.org.

**Closed by tanner0101** 2017-04-27 11:34 UTC
Labels: bug, requires 3rd party
