### ISSUE TITLE
First request to a CredentialsAuthenticator or AsyncCredentialsAuthenticator fails if the body is too large

### ISSUE THREAD

**Issue by owainhunt** [vapor/vapor#2735] opened 2021-11-14 20:35 UTC
### Describe the bug

When using a route protected by an AsyncCredentialsAuthenticator, the first request to the route fails if the body is too large (in my testing, above 1795 bytes). Subsequent requests to the same route succeed as expected. 

It appears to fail at the point the authenticator attempts to decode the request body - see `Authentication+Concurrency.swift:AsyncCredentialsAuthenticator.authenticate(request:)`: https://github.com/vapor/vapor/blob/80750314e0d9ae11b3886df7f43f495b0661d2dc/Sources/Vapor/Concurrency/Authentication%2BConcurrency.swift#L87 
The error message suggests the request body is empty. Indeed if you put a breakpoint at that line, `po request.body.string` returns nil. 

Error message is as follows:

```
"message" : "Request body is empty. If you're trying to stream the body, decoding streaming bodies not supported",
  "request-id" : "38650034-1563-4198-9482-54C36E88177F",
  "severity" : "DEBUG",
  "sourceLocation" : {
    "file" : "Vapor/Request/Request.swift",
    "function" : "decode(_:using:)",
    "line" : 77
  },
``` 

### To Reproduce

Define an AsyncCredentialsAuthenticator:
```swift
class DummyAuth: AsyncCredentialsAuthenticator {
    typealias Credentials = String
    func authenticate(credentials: Credentials, for request: Request) async throws {
        request.auth.login(credentials)
    }
}
```

Protect a route with an instance of that authenticator:
```swift
app.grouped(Dummy()).grouped(String.guardMiddleware()).post("blah") { req -> Response in
        Response(status: .ok)
    }
```

Run the app and make two requests, with a body length of greater than 1795 bytes.

### Expected behavior

Both requests will succeed with a 200 response.

### Actual behaviour

First request fails with a 401:

```
{
    "error": true,
    "reason": "String not authenticated."
}
```

Second request succeeds with a 200.

### Environment

* Vapor Framework version: 4.52.2
* OS version: Monterey 12.0.1

**Comment by 0xTim** [comment] 2021-11-16 02:20
@owainhunt Just to confirm the non-async version works fine?

**Comment by owainhunt** [comment] 2021-11-16 11:43
@0xTim I'd not looked at the non-async version, but in my testing the below code behaves in exactly the same way - with a body above a certain size, the first request fails but subsequent requests succeed.

```swift
class DummyAuthFuture: CredentialsAuthenticator {
    
    typealias Credentials = String
    
    func authenticate(credentials: Credentials, for request: Request) -> EventLoopFuture<Void> {
        request.auth.login(credentials)
        return request.eventLoop.makeSucceededFuture(())
    }
}
```

**Comment by 0xTim** [comment] 2021-11-16 11:52
I wonder if this is related to #2494 and that over a certain size (probably the size of the ByteBuffer) it fails to decode the entire body. Does adding `request.body.collect(max: nil)` to the middleware fix it?

**Comment by owainhunt** [comment] 2021-11-16 12:19
These _seem_ to work in some basic testing:

```swift
extension AsyncCredentialsAuthenticator {
    public func authenticate(request: Request) async throws {
        
        _ = try await request.body.collect(max: nil).get()

        let credentials: Credentials
        do {
            credentials = try request.content.decode(Credentials.self)
        } catch {
            return
        }
        return try await self.authenticate(credentials: credentials, for: request)
    }
}
```

```swift
extension CredentialsAuthenticator {
    public func authenticate(request: Request) -> EventLoopFuture<Void> {
        
        return request.body.collect(max: nil).flatMap { _ -> EventLoopFuture<Void> in
        
            let credentials: Credentials
            do {
                credentials = try request.content.decode(Credentials.self)
            } catch {
                return request.eventLoop.makeSucceededFuture(())
            }
            return self.authenticate(credentials: credentials, for: request)
        }
    }
}
```

Still not sure why it would previously fail the first time and then work on subsequent requests, though.

**Comment by 0xTim** [comment] 2021-11-16 12:22
My guess would be the event loop buffer would be increased after the decode or something like that. It would have to be something specific to the event loop and not the request. 

Whatever it is it's definitely a bug

**Comment by grennis** [comment] 2022-05-20 09:48
I have also seen this problem, with somewhat different symptoms because I am not using an authenticated route. The first request with a large post body (in my case, ~600KB) will often hang (like 1 in 10 times) because my route handler is never called.  Note that my middleware handlers are called as normal.

It's not _always_ the first request - it does happen on subsequent requests, but very much more rarely.

After reading this issue, I tried using this as the first middleware as a workaround, and it did indeed fix the problem - no more hangs or crashes, on any os:

```
class ConsumeBodyMiddleware: Middleware {
    func respond(to request: Request, chainingTo next: Responder) -> EventLoopFuture<Response> {
        request.body.collect(max: ("50mb" as ByteCount).value)
            .flatMap { _ in
                next.respond(to: request)
            }
    }
}

```

**Comment by 0xTim** [comment] 2022-05-23 10:11
The underlying issue is #2742, will close it in favour of that one. It's being looked at

**Closed by 0xTim** 2022-05-23 10:11 UTC
Labels: bug

**Comment by marius-se** [comment] 2022-08-31 10:58
@owainhunt @grennis can you still reproduce this? I'm currently investigating this issue, but couldn't reproduce it so far.
