### ISSUE TITLE
Template demo feature todos NOT working

### ISSUE THREAD

**Issue by IvanChan** [vapor/vapor#2554] opened 2021-01-15 07:18 UTC
I don't really know what to say about template demo NOT working.
It's totally NOT friend for newer.

MacOS Bigsur

vapor new helloworld
use fluent & mysql

run succeed and see `It works`, but the demo feature `todos` is NOT working & don't know what happen.

further more
if u select fluent & mysql & leaf, u will find db config code is missing

**Comment by 0xTim** [comment] 2021-01-25 12:06
As discussed in the docs, you need to trigger the migrations somehow - https://docs.vapor.codes/4.0/fluent/migration/#migrate

I'm happy to add this to the template under development or similar. 

As for the DB config code, I can't reproduce that. This is what I get with those options:

```swift
    app.databases.use(.mysql(
        hostname: Environment.get("DATABASE_HOST") ?? "localhost",
        port: Environment.get("DATABASE_PORT").flatMap(Int.init(_:)) ?? MySQLConfiguration.ianaPortNumber,
        username: Environment.get("DATABASE_USERNAME") ?? "vapor_username",
        password: Environment.get("DATABASE_PASSWORD") ?? "vapor_password",
        database: Environment.get("DATABASE_NAME") ?? "vapor_database"
    ), as: .mysql)

    app.migrations.add(CreateTodo())

    app.views.use(.leaf)
```

I'll close this issue, but feel free to open issues in vapor/template if you have any other bugs

**Closed by 0xTim** 2021-01-25 12:06 UTC
Labels: bug
