### ISSUE TITLE
Server doesn't stop succesfully in CLI after opening WebSocket connections

### ISSUE THREAD

**Issue by MaxDesiatov** [vapor/vapor#2451] opened 2020-07-24 15:26 UTC
### Steps to reproduce

Create a simple Vapor app that opens WebSocket connections:

```swift
import Vapor

extension Application {
  func configure(
    onWebSocketOpen: @escaping (WebSocket) -> (),
    onWebSocketClose: @escaping (WebSocket) -> ()
  ) {
    webSocket("watcher") { _, ws in
      onWebSocketOpen(ws)
      ws.onClose.whenComplete { _ in onWebSocketClose(ws) }
    }
  }
}

final class Server {
  private struct Lifecycle: LifecycleHandler {
    weak var server: Server?

    /// Closes all active WebSocket connections
    func shutdown(_ app: Application) {
      try! EventLoopFuture<()>.andAllSucceed(
        server?.connections.map { $0.close() } ?? [],
        on: app.eventLoopGroup.next()
      ).wait()
      print("shutdown finished")
    }
  }

  private var connections = Set<WebSocket>()
  private let app: Application

  init() throws {
    var env = Environment(name: "development", arguments: ["vapor"])
    try LoggingSystem.bootstrap(from: &env)
    app = Application(env)
    app.configure(
      onWebSocketOpen: { [weak self] in
        self?.connections.insert($0)
      },
      onWebSocketClose: { [weak self] in
        self?.connections.remove($0)
      }
    )
  }

  /// Blocking function that starts the HTTP server
  func run() throws {
    defer { app.shutdown() }
    app.lifecycle.use(Lifecycle(server: self))
    try app.run()
  }
}

try Server().run()
```

### Expected behavior

When this server app is started from command-line and any WebSocket connections are established, the server process can stopped quickly with Ctrl-C.

### Actual behavior

The server process can't be stopped quickly with Ctrl-C. It hangs for about 5 seconds or so and then raises the following error:

```
shutdown finished
[ ERROR ] Could not stop HTTP server: Abort.500: Server stop took too long.
ERROR: Cannot schedule tasks on an EventLoop that has already shut down. This will be upgraded to a forced crash in future SwiftNIO versions.
```

### Environment

These are the details of revelant package dependencies from `Package.resolved`:

```
      {
        "package": "vapor",
        "repositoryURL": "https://github.com/vapor/vapor.git",
        "state": {
          "branch": null,
          "revision": "88293674e2ea017691c56af20d0938dfff7ece04",
          "version": "4.27.0"
        }
      },
      {
        "package": "websocket-kit",
        "repositoryURL": "https://github.com/vapor/websocket-kit.git",
        "state": {
          "branch": null,
          "revision": "b0736014be634475dac4c23843811257d86dcdc1",
          "version": "2.1.1"
        }
      }
```

* Vapor Framework version: 4.27.0, but this was reproducible in versions as old as 4.5.0
* Vapor Toolbox version: not installed
* OS version: macOS 10.15.6

**Comment by 0xTim** [comment] 2020-07-24 22:09
This happens on regular routes as well I've seen

**Comment by tanner0101** [comment] 2020-07-27 20:37
Hey @MaxDesiatov thanks for reporting. I'm not able to recreate this one locally. Would you mind giving more information on how to recreate this? 

The steps I tried were:
- Run sample code provided
- Connect websocket client (I used https://apps.apple.com/us/app/websocket-client/id1399498094?mt=12) 
- Stop server with client connected

I tried this several times and it always worked fine. 

A couple notes on things I had to change to get your sample running:

1: Move `app.shutdown()` to `Server.deinit`. 

Otherwise the app would shutdown right after it was started. 

2: Add `readLine()` to allow shutdown to run from Xcode

Xcode only allows sending SIGKILL, so I added a `readLine()` that lets me simulate `^C` from inside of Xcode. 

3: WebSocket hashable conformance

Here's the sample project I was testing against:

[websocket-stuck.zip](https://github.com/vapor/vapor/files/4984275/websocket-stuck.zip)

**Comment by fouadhatem** [comment] 2020-08-10 22:19
Hi @tanner0101 

I was able to recreate this in the following manner on both Catalina 10.15.6 and Ubuntu. I'll lay out the procedure for linux as tried out on a VM:

1. Start with fresh minimal install of Ubuntu Server 16.04 (also reproduced on 18.04 and 20.04).
2. Download Swift dependencies as outlined in swift.org.
3. Download and install latest Swift toolchain (5.2.5 for linux) from swift.org and verify that it is running.
4. Clone Vapor toolbox from GitHub: `$git clone https://github.com/vapor/toolbox` and build after switching into toolbox directory: `$swift build -c release --disable-sandbox --enable-test-discovery`.
5. Copy build product to /usr/local/bin `$sudo mv .build/release/vapor /usr/local/bin`
6. Verify vapor runs by executing `vapor --version` or `vapor --help` (by the way, while you're at it, check out the response you get from the `--version` option at this stage, particularly the toolbox version).
7. Switch to a desired working directory and create a new vapor project: `vapor new hello-vapor` without fluent.
8. Switch to your new project directory and build your new project using `vapor build`
9. Run the project with the bind option `-b` to attempt to access it from a different machine: `vapor run serve -b <IP address>:<port number>`
10. Open a browser in a different (or host) machine and visit the IP address and port combination you used to verify that it works and is accessible.
11. Terminate the server with CTRL-C and wait for a few seconds.

The error should appear at the CL prompt on your Vapor machine.

**Comment by tanner0101** [comment] 2020-08-13 19:23
@fouadhatem hmm I'm still not able to recreate locally. Could you share how you triggered this on macOS? Including which version of Xcode and Swift you're using?

**Comment by fouadhatem** [comment] 2020-08-13 23:23
@tanner0101 I did some further digging into this and here is what I was able to come up with:

- The issue appears to be sporadic on macOS. There are times when terminating an application from Xcode exits with code 9 and rebuilding/running it within Xcode continues to work fine. There are other times when attempting to build/run the project a SECOND time exits with code -1, along with an error message indicating that the address (default: 127.0.0.1:8080) is in use. Attached is the `Package.resolved` file for the project I used to test this on macOS (version: 10.15.6 including the latest supplemental update and Xcode version: 11.6).

- When the issue does occur on macOS, the server continues to be responsive even though the project is terminated on Xcode. A quick check on Activity Monitor shows me a program called Run that must be terminated using Force Quit in order to terminate the server and be able to successfully build the project again.

- The issue is consistent on Linux. The bug appears every single time I attempt it on any Ubuntu release (16.04, 18.04, 20.04).

- The issue continues to persist with the latest release of Vapor 4.27.3 on both macOS (sporadically) and Linux (consistently).

- Ubuntu 20.04 was able to give me a little more info to indicate where the problem might be. Below are the error messages received (the last error was repeated twice every time):

```
[ERROR] Could not stop HTTP server: abort.500: Server stop took too long.
ERROR: Cannot schedule tasks on an EventLoop that has already shut down. This will be upgraded to a forced crash in future SwiftNIO versions.
ERROR: Cannot schedule tasks on an EventLoop that has already shut down. This will be upgraded to a forced crash in future SwiftNIO versions.
```

**Comment by MaxDesiatov** [comment] 2020-08-14 09:04
> Terminating the project with CTRL-C on Linux (or with the stop button on Xcode) will NOT generate the error if no web sockets were created.

This is exactly what I'm observing. It's reproducible in [carton](https://github.com/swiftwasm/carton) with any SwiftWasm project on macOS as soon as even a single WebSocket connection is established.

**Comment by tanner0101** [comment] 2020-08-14 16:14
@fouadhatem this seems like the critical piece: 

> Terminating the project with CTRL-C on Linux (or with the stop button on Xcode) will NOT generate the error if no web sockets were created.

Especially with what @MaxDesiatov is saying. Could you share the WebSocket code you are using? If you have a project that recreates this even sporadically on macOS that would be helpful. 

You last comment said to do:

> Switch to a desired working directory and create a new vapor project: vapor new hello-vapor without fluent.

Which doesn't include any WebSocket code so that was confusing me a bit. 

I did try to recreate this from Max's example here:

> Here's the sample project I was testing against:
> [websocket-stuck.zip](https://github.com/vapor/vapor/files/4984275/websocket-stuck.zip)

But I couldn't get a repro even after many tests. So it seems like there's a particular usage / edge case in WebSocket that is causing this. Seeing your code in particular would be helpful here. Especially if you can get it down to a small reproducible sample. If that's not possible I can try digging into carton but if I can get a small repro going that will be the fastest way to solve this.

**Comment by MaxDesiatov** [comment] 2020-08-14 16:31
As I said, the most stably reproducible (100% of the time as long as at least one WebSocket connection is established) example for me is the [carton](https://github.com/swiftwasm/carton) project. I tried to isolate the WebSocket code as much as I can in the original post, you can see it in full [here](https://github.com/swiftwasm/carton/blob/main/Sources/carton/Server/Server.swift).

**Comment by MaxDesiatov** [comment] 2020-08-14 16:32
The is also reproducible with any browser WebSocket client, I tried Chrome, Firefox and Safari on macOS.

**Comment by tanner0101** [comment] 2020-08-14 16:34
@MaxDesiatov which OS / Swift version are you using? I'm trying your code again here (only change is adding WebSocket hashable conformance) and I can't get it to repro. 

> The is also reproducible for me with any browser WebSocket client, I tried Chrome, Firefox and Safari on macOS.

~~Could you share the code you are using to create that client?~~ thanks!

> As I said, the most stably reproducible (100% of the time as long as at least one WebSocket connection is established) example for me is the carton project.

Maybe I should just dig into carton directly then. What's the easiest way to get that up and running locally?

**Comment by MaxDesiatov** [comment] 2020-08-14 16:36
You can clone the project and run these commands in the project root to get the server started:

```
swift build && cd TestApp && ../.build/debug/carton dev --product TestApp
```

Xcode 11.6 is the recommended version to build `carton`.

**Comment by MaxDesiatov** [comment] 2020-08-14 16:39
As for the client, after `carton dev` started you can open `http://127.0.0.1:8080/` in any browser to get the connection established.

**Comment by tanner0101** [comment] 2020-08-14 16:40
Perfect, I'm able to repro now. Digging in. Thanks!

**Comment by tanner0101** [comment] 2020-08-14 17:02
It does look to be an issue with the WebSocket client. If I use https://apps.apple.com/us/app/websocket-client/id1399498094?mt=12 there's no issue. But visiting `localhost:8080` in the browser and using the JS WebSocket client reproduces it consistently. One of the packages must be handling close incorrectly. I'm looking into that.

The other thing I noticed is that your example posted here contains a `LifecycleHandler` for closing connections before shutdown. However, that seems to be missing from `carton`? That should be there otherwise WebSockets will remain open preventing the HTTP server from shutting down as expected. I've added this `LifecycleHandler` temporarily (although maybe it exists elsewhere and I'm missing it?).

**Comment by MaxDesiatov** [comment] 2020-08-14 17:36
Did `LifecycleHandler` help though in your case? I've tried adding it, but it didn't have any effect. I've added it to the OP example just to make sure that the sequence of events is correct in log output.

**Comment by fouadhatem** [comment] 2020-08-14 17:39
@tanner0101 there's no web socket code at all in my project, just the standard vapor project template. Any browser does the trick (Chrome, Firefox, Safari). 

> One of the packages must be handling close incorrectly. I'm looking into that.

Looks like it.

> The other thing I noticed is that your example posted here contains a LifecycleHandler for closing connections before shutdown. However, that seems to be missing from carton? That should be there otherwise WebSockets will remain open preventing the HTTP server from shutting down as expected. I've added this LifecycleHandler temporarily (although maybe it exists elsewhere and I'm missing it?).

I am able to reproduce this error on Linux straight from the standard vapor template (without any additional code) by simply creating a new project with `vapor new`, building it with `vapor build` and running it with `vapor run serve -b <IP address>:<PORT>`, visiting the address with browser and then terminating the server with `CTRL-C`.

**Comment by tanner0101** [comment] 2020-08-14 19:12
I think I've finally tracked down the issue. There appears to be two things going on here:

### 1: carton is not closing WebSocket connections

Basically what `LifecycleHandler` was doing in the original post. Or just doing it manually like this:

```diff
diff --git a/Sources/carton/Server/Server.swift b/Sources/carton/Server/Server.swift
index f659264..7ba83db 100644
--- a/Sources/carton/Server/Server.swift
+++ b/Sources/carton/Server/Server.swift
@@ -90,5 +90,8 @@ final class Server {
   func run() throws {
     defer { app.shutdown() }
     try app.run()
+    for conn in self.connections {
+        try conn.close().wait()
+    }
   }
 }
```

This fixes the issue if _only the /watcher route_ is hit. However, there is a second source of open connections.

### 2: Safari is keeping an HTTP connection alive

The one used to fetch the `/main.wasm` route specifically. If (1) is fixed and you wait more than ~30 seconds before trying to shut the server down, then there will be no issue. This seems to be because Safari is holding onto the "keep-alive" connection it used to fetch resources for a period time. This would also explain other reports of the "server cannot shutdown" error that I've been unable to recreate.

I added a small patch to Vapor's HTTP request decoder to intercept the server quiesce event and manually close keep-alive requests that are inactive. I'm not sure this logic is correct so I want to double check with the NIO team before patching it. But with this logic in place, shutdown in `carton` begins to work reliably. 

```diff
--- a/Sources/Vapor/HTTP/Server/HTTPServerRequestDecoder.swift
+++ b/Sources/Vapor/HTTP/Server/HTTPServerRequestDecoder.swift
@@ -179,7 +180,8 @@ final class HTTPServerRequestDecoder: ChannelInboundHandler, RemovableChannelHan
     }
 
     func userInboundEventTriggered(context: ChannelHandlerContext, event: Any) {
-        if event is HTTPServerResponseEncoder.ResponseEndSentEvent {
+        switch event {
+        case is HTTPServerResponseEncoder.ResponseEndSentEvent:
             switch self.requestState {
             case .streamingBody(let bodyStream):
                 // Response ended during request stream.
@@ -197,6 +199,16 @@ final class HTTPServerRequestDecoder: ChannelInboundHandler, RemovableChannelHan
                 // Response ended after request had been read.
                 break
             }
+        case is ChannelShouldQuiesceEvent:
+            switch self.requestState {
+            case .ready:
+                self.logger.trace("Closing keep-alive HTTP connection since server is going away")
+                context.channel.close(mode: .all, promise: nil)
+            default:
+                self.logger.debug("Can't quiesce because request is in-flight: \(event)")
+            }
+        default:
+            self.logger.trace("Unhandled user event: \(event)")
         }
     }
 }
```

**Comment by tanner0101** [comment] 2020-08-14 19:14
> Any browser does the trick (Chrome, Firefox, Safari).

@fouadhatem yup that was the key piece I was missing.  I should have paid closer attention to this from your first post:

> Open a browser in a different (or host) machine and visit the IP address and port combination you used to verify that it works and is accessible.

I had been using `curl` instead.

**Comment by MaxDesiatov** [comment] 2020-08-14 19:15
Awesome, thank you very much for the detailed investigation! Do I understand correctly that even if I add patch 1 on my side, I still need to wait for patch 2 to land either in Vapor or NIO?

**Comment by tanner0101** [comment] 2020-08-14 19:17
@MaxDesiatov yes. Although you should be able to work around (2) with something like:

```diff
--- a/Sources/carton/Server/Application.swift
+++ b/Sources/carton/Server/Application.swift
@@ -47,9 +47,11 @@ extension Application {
       ws.onClose.whenComplete { _ in onWebSocketClose(ws) }
     }
 
-    get("main.wasm") { (request: Request) in
+    get("main.wasm") { (request: Request) -> Response in
       // stream the file
-      request.eventLoop.makeSucceededFuture(request.fileio.streamFile(at: mainWasmPath))
+      let res = request.fileio.streamFile(at: mainWasmPath)
+      res.headers.replaceOrAdd(name: .connection, value: "close")
+      return res
     }
   }
 }
```

That will force the browser to not keep the connection alive.

**Comment by tanner0101** [comment] 2020-08-14 19:20
> Side Note: the --version switch also seems to not find the toolbox on Linux after installing it. It works on macOS though.

@fouadhatem that's because building the toolbox from source doesn't have a version. The way macOS discovers the version is by asking Homebrew. However, if you build from source, it doesn't have any idea which git tag or branch you used. It might be worth making the error message clearer here (or figuring out how to detect which branch / git tag was used).

**Comment by MaxDesiatov** [comment] 2020-08-14 19:22
Right, and as for patch 1, would it make more sense for Vapor to close WebSocket connections automatically in (some, I'm not sure which) `deinit`? I assume that connections are deallocated after `Application`  is deallocated, which I previously expected closes all connections. Otherwise we'll need to clarify this in Vapor docs, but this may still be too cumbersome for users, so wouldn't you prefer the default behaviour to change to closing connections automatically?

**Comment by fouadhatem** [comment] 2020-08-14 19:24
> > Side Note: the --version switch also seems to not find the toolbox on Linux after installing it. It works on macOS though.
> 
> 
> 
> @fouadhatem that's because building the toolbox from source doesn't have a version. The way macOS discovers the version is by asking Homebrew. However, if you build from source, it doesn't have any idea which git tag or branch you used. It might be worth making the error message clearer here (or figuring out how to detect which branch / git tag was used). 

Makes sense. Would you like me to create a new issue with this and label it as an enhancement?

**Comment by tanner0101** [comment] 2020-08-14 19:45
> Right, and as for patch 1, would it make more sense for Vapor to close WebSocket connections automatically in (some, I'm not sure which) deinit?

@MaxDesiatov I agree this is not as easy / obvious as it could be. I think I need to do a bit more research here to see how other libraries handle this. The problem is that Vapor is not the one holding onto these WebSockets. The `app.webSocket` closure simply gives you the WebSocket as it comes in. In carton's case, it's the `Server` type that is holding onto these WebSockets and keeping them alive. So, it makes sense that `Server` should also be responsible for closing them down. If Vapor were to also be keeping track of these connections and attempting to close them, things could get weird. Maybe this is the right move though. Another option would be Vapor offering a higher level API or providing better documentation for how to properly manage active WebSocket connections. 

> Makes sense. Would you like me to create a new issue with this and label it as an enhancement?

@fouadhatem yes I would appreciate that!

**Comment by tanner0101** [comment] 2020-08-14 20:03
I've confirmed with the NIO team that `ChannelShouldQuiesceEvent` is indeed meant to be used in this way. Patch incoming.

**Comment by fouadhatem** [comment] 2020-08-14 20:15
@tanner0101 I'm thinking now that vapor/websocket-kit#76 the same issue?

**Comment by tanner0101** [comment] 2020-08-14 20:53
@fouadhatem it's possible that is related. I'm still not 100% sure though.

**Comment by tanner0101** [comment] 2020-08-14 20:59
@MaxDesiatov let me know if 4.28.0 works for you.

**Closed** 2020-08-14 20:58 UTC
Labels: bug

**Comment by MaxDesiatov** [comment] 2020-08-14 21:06
Fantastic, it does, thanks for your help!

**Comment by fouadhatem** [comment] 2020-08-14 21:47
Works for me as well! Thanks @tanner0101 and @MaxDesiatov
