### ISSUE TITLE
Why SwiftPackageManager fetch Vapor so slow?

### ISSUE THREAD

**Issue by dushandz** [vapor/vapor#2355] opened 2020-05-12 14:22 UTC
I followed [Vapor4.0 doc](https://docs.vapor.codes/4.0/hello-world/)

### Steps to reproduce

`vapor-beta new hello -n`

when i open `Package.swift` file with Xcode, Xcode start to fetch vapor,  very slow. it took me 20 minutes.
But when i type `Vapor-beta  build` , it run the `hello-world` demo very smoothly. 
Why?
I can not start to develop with Xcode, Because it always fetch vapor. Is there any other way to start? Clone vapor to my mac and update `Package.swift` vapor git path to local?

### Environment

* Vapor Framework version:
Vapor-beta 4.0
* Vapor Toolbox version:
Vapor Toolbox: 3.1.10
* OS version:
macOS10.15.4
* Xcode version:
Xcode 11.4.1

**Comment by 0xTim** [comment] 2020-05-18 15:16
@dushandz it can be caused by a number of problems, including internet connections, proxy issues or an invalid manifest file. Can you post your Package.swift? I'm closing this as this is probably an Xcode issue that should be reported at feedbackassistant.apple.com

**Closed by 0xTim** 2020-05-18 15:16 UTC
