### ISSUE TITLE
Graphiti integration ?

### ISSUE THREAD

**Issue by maximveksler** [vapor/vapor#1850] opened 2018-12-11 08:48 UTC
What integrations with GraphQL for Vapor are available? 

Are there middleware like the following https://github.com/lgaches/Kitura-GraphQL only for Vapor?

**Comment by halfnibble** [comment] 2020-01-06 05:11
To my knowledge, there is currently no officially supported GraphQL middleware.

However, you can setup your own GraphQL service using Vapor. See the comments in this closed issue: #1454 

I too would like to see official GraphQL support at some point, so maybe we could add that as a feature request for down the road?

(Possible duplicate of #1454)

**Closed** 2020-04-01 21:42 UTC
Labels: question
