### ISSUE TITLE
Add ability to add custom validations that can access multiple data fields

### ISSUE THREAD

**Issue by cgriffin** [vapor/vapor#2563] opened 2021-02-04 22:32 UTC
In Vapor 3 you could add a custom validation like so:

 ```
   validations.add("passwords match") { model in
      guard model.password == model.confirmPassword else {
        throw BasicValidationError("passwords don’t match")
      }
    }

```

I'm requesting that this ability or something like it be added to Vapor 4.

**Comment by 0xTim** [comment] 2023-11-01 18:55
Closing as a duplicate of #1819

**Closed by 0xTim** 2023-11-01 18:55 UTC
Labels: enhancement
