### ISSUE TITLE
"backgroundExecute(127, [], [])" Error when running with sudo

### ISSUE THREAD

**Issue by tdeleon** [vapor/vapor#675] opened 2016-10-28 18:09 UTC
OS: Ubuntu 16.04, 16.10

I first changed the port in servers.json to 80, which then requires sudo to run.
When attempting to run vapor under sudo (_vapor run serve_), it fails with the error: _Error: backgroundExecute(127, [], [])_.

**Steps to Reproduce**

1 Create a new project: 

> vapor new Hello
> cd Hello

2 Edit Config/servers.json to use the static IP & port 80:

> {
>        "default": {
>                "port": "$PORT:80",
>                "host": "x.x.x.x",
>                "securityLayer": "none"
>        }
> }

3 Try to run - will fail without sudo

> $ vapor run serve
> Running Hello...
> No preparations.
> Server 'default' starting at x.x.x.x:80
> Could not bind to x.x.x.x:80, it may be in use or require sudo.

4 Try again with sudo - fails with error

> $ sudo vapor run serve
> Error: backgroundExecute(127, [], [])

**Comment by reza-ryte-club** [comment] 2016-10-28 23:06
Checked in macOS Sierra with port number 8088. No problem occurred.
Could you please check this with other ports?

**Comment by tdeleon** [comment] 2016-10-28 23:18
Same issue with other ports (when sudo is used), tried 8080 & 8088.

**Comment by reza-ryte-club** [comment] 2016-10-29 06:00
Trying to reproduce this issue in docker. If I can't then I will use virtualbox.

**Comment by reza-ryte-club** [comment] 2016-10-29 10:07
Failed to install vapor from docker. Installing ubuntu 16.10 in virtualbox.

**Comment by reza-ryte-club** [comment] 2016-10-30 04:35
I've figured out the reason I suppose. The  "backgroundExecute(127, [], [])" error means the console throws back error number 127, which is a bash returned value for not having the command. 
That means, somehow your computer is not getting the necessary paths of the dependent libraries.

Then I checked my $PATH variable settings in in macOS for my username as well as root user.
For my username, I found this:

**echo $PATH**
_/Users/reza/.swiftenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin_

then I switched to root by this command:
**sudo -i**
after giving **echo $PATH** command I got the same result in macOS.
_/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/reza/.swiftenv/shims_

But in Ubuntu 16.04 I got different results for root user.
For my regular user account I got this result for **echo $PATH**
_/swift-3.0/usr/bin:/home/reza/bin:/home/reza/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin_

But for root user I got different paths where swift related path values are missing
_/usr/local/sbin:/usr/local/bin:/usr/bin:/sbin:/bin:/snap/bin_

I then added the values temporarily by this command
**PATH=$PATH:/swift-3.0/usr/bin**

Then I installed vapor and creates a new project. It works fine now if I switch to root.

**Comment by tdeleon** [comment] 2016-10-30 07:43
Looks like this is a security feature of sudo on Ubuntu which always overwrites the path to "safe" locations. There's a workaround [here](http://askubuntu.com/questions/599165/why-is-sudo-not-working-with-exported-path) where the path can be changed with the **secure_path** variable in /etc/sudoers to add the swift install directory. I suppose you could also do symlinks from /swift-3.0/usr/bin/.

You might want to consider making a note of this in the Vapor docs on the _Install Swift 3: Ubuntu_ page, or under _Hello World_ in where it mentions running under sudo. I just used the swift.vapor.sh/ubuntu script to install Swift, so using that (with the /swift-3.0 install location) will always run into this issue on Ubuntu.

**Comment by reza-ryte-club** [comment] 2016-11-02 06:08
Added the instruction to the vapor documentation, please close this issue.
https://github.com/vapor/documentation/pull/67#event-843358667

**Closed** 2016-11-02 06:10 UTC
