### ISSUE TITLE
MySQL cannot save long strings (over 252 chars long)

### ISSUE THREAD

**Issue by TomShen1234** [vapor/vapor#2302] opened 2020-04-10 01:26 UTC
[Original issue posted here.](https://github.com/vapor/mysql-kit/issues/270)

This placeholder issue can be closed after tagging the original issue in MySQLKit.

**Comment by Joannis** [comment] 2020-04-10 12:56
Although it's not the ideal place for an issue, it's good that you posted it here since I'm sure it was overlooked in the other issues section. Ping @gwynne or @tanner0101 .

**Comment by tanner0101** [comment] 2020-04-16 15:35
Duplicate of https://github.com/vapor/mysql-kit/issues/270.

**Closed by tanner0101** 2020-04-16 15:35 UTC
Labels: bug
