### ISSUE TITLE
Error after installing Vapor using custom location of `Homebrew` on macOS

### ISSUE THREAD

**Issue by vgorloff** [vapor/vapor#1211] opened 2017-10-21 20:01 UTC
* Vapor Version: 2.0
* OS: macOS
* OS Version: 10.12.6 (16G29)
* Vapor Toolbox Version: ???

I'm using custom location of `Homebrew` on macOS. It is not in `/usr/local/`, but in `~/.homebrew` folder.

### Expected Behavior

Setup following [Getting started](https://docs.vapor.codes/2.0/getting-started/install-on-macos/) guide working using custom location of `Homebrew`. 

### Current Behavior

```
$ vapor --help
dyld: Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
  Referenced from: /Users/_USERNAME_/.homebrew/bin/vapor
  Reason: image not found
```

### How to Reproduce

1. Install `Homebrew` to custom location:
```
git clone https://github.com/Homebrew/brew.git ~/.homebrew
export PATH=$HOME/.homebrew/bin:$HOME/.homebrew/sbin:$PATH
```
2. Install Vapor following [Getting started](https://docs.vapor.codes/2.0/getting-started/install-on-macos/) 
3. Launch `vapor --help`

### Workaround

Create symbolic link from custom `homebrew` installation:

```
sudo ln -s /Users/_USERNAME_/.homebrew/opt/ /usr/local
```

### Additional information

Seems executable `vapor` linked using absolute path `/usr/local/opt/openssl/lib/libssl.1.0.0.dylib` while it can be linked using relative path `@rpath/../../../opt/openssl/lib/libssl.1.0.0.dylib`.

**Comment by Joannis** [comment] 2017-10-21 20:21
Thanks for the report! I'll make sure we'll pick this up on Monday or Tuesday.

**Comment by tanner0101** [comment] 2017-10-25 21:02
this is an issue w/ vapor/toolbox. the specific script we use to compile and distribute is here: https://github.com/vapor/toolbox/blob/master/distribute.sh

@vgorloff perhaps you see something in that script that could be changed to accommodate custom homebrew installs?

**Comment by vgorloff** [comment] 2017-10-25 21:42
Nothing special in `distribute.sh` script. Probably it is something in dependencies. Will try to look on it this week later or next week...

**Comment by vzsg** [comment] 2017-10-26 08:01
The problem is that Toolbox v3 depends on OpenSSL, which is linked with an absolute path automatically by the toolchain. To make it relocatable, distribute.sh should use `install_name_tool` to rewrite the absolute path to the one in the original issue.

**Comment by rbq** [comment] 2018-05-07 11:29
Thanks, `sudo ln -s /usr/local/homebrew/opt /usr/local/` worked for me.

**Comment by MrLotU** [comment] 2019-01-31 07:42
As of November 2018 Vapor 2 is no longer supported. Closing this issue. [Version support](https://docs.vapor.codes/3.0/version/support/)

**Closed by MrLotU** 2019-01-31 07:42 UTC

**Comment by vzsg** [comment] 2019-01-31 09:00
Note that this is a toolbox issue, not a Vapor framework issue.

**Comment by MrLotU** [comment] 2019-01-31 09:06
Oh, oops. My bad, in that case though, I propose this issue either:
Stays closed since we have a workaround/solution in this thread
Is moved to the toolbox repo so a fix can be implemented

**Comment by vzsg** [comment] 2019-01-31 09:39
I made a new issue there with the gist.

**Comment by MrLotU** [comment] 2019-01-31 09:40
Thanks!
