### ISSUE TITLE
Vapor server crashes when handling async stream uploads

### ISSUE THREAD

**Issue by gjcairo** [vapor/vapor#3202] opened 2024-05-29 09:43 UTC
### Describe the issue

Vapor server crashes when handling async stream uploads

### Vapor version

4.101.0

### Operating system and version

ubi9 minimal Docker container on macOS 14.5

### Swift version

5.10

### Steps to reproduce

When running async stream requests (particularly, when uploading binary data via an async stream), one of the server's ELs will eventually crash, or rather hang silently, causing the client to hang as well.
The server will keep on running and is able to service other requests via other ELs.
You can reproduce this with a simple program that streams the data, like this one:
```swift
@main struct TestServer {
  static func main() async throws {
    let app = try await Vapor.Application.make()
    app.on(.POST, "testasyncstream", body: .stream) { request in
      var totalBytes = 0
      for try await chunk in request.body {
        totalBytes += chunk.readableBytesView.count
      }
      print("Read \(totalBytes) bytes from request")
      return HTTPResponseStatus(statusCode: 202)
    }
   try await app.execute()
  }
}
```

If you execute multiple requests of binary data uploading (~14MB should be enough), you will eventually hit the issue described above. It may take several iterations.

```
while true; do
 curl -s -w '%{http_code}\n' -X POST --data-binary "@${_test_file}" -H 'Content-Type: application/octet-stream' 'http://localhost:8080/testasyncstream'
done
```

### Outcome

The stacktrace on the server shows this when it hangs:
```
2024-05-15T13:12:35+0000 info codes.vapor.application : request-id=EC730688-AD72-405B-8CD3-F3969F00840C [Vapor] POST /testasyncstream
Process 16 stopped
thread #2, name = 'NIO-SGLTN-0-#0', stop reason = signal SIGTRAP
 frame #0: 0xffffffffffffffff 
```

**Comment by ptoffy** [comment] 2024-10-08 12:19
Closing this as a duplicate of #2985. We've added a test in #3232 for this exact code and the PR seems to solve it

**Closed by ptoffy** 2024-10-08 12:19 UTC
Labels: bug
