### ISSUE TITLE
Random Delayed Crashes

### ISSUE THREAD

**Issue by yousifKashef** [vapor/vapor#2727] opened 2021-11-03 14:28 UTC
I'm running two fairly different vapor apps on two Ubuntu servers. Both are set up with supervisor as recommended by the vapor documentation. Both the apps seem to crash after about a day or two. 

How do I find out exactly why they crashed? does supervisor have a way of telling me that? also, how do I have supervisor restart the app when it crashed, not just when the server restarts?

**Comment by yousifKashef** [comment] 2021-11-03 14:42
I'm wondering if this is related to issue #2722. or does that just affect the app's build and not run process?

**Comment by fouadhatem** [comment] 2021-11-03 15:17
@yousifKashef please add more info about your environment (machine specs, Vapor version, modules, etc.) This may help narrow down the cause.

**Comment by yousifKashef** [comment] 2021-11-03 15:34
Hi Fouad

The machines are on  Ubuntu 18.04.6 LTS (GNU/Linux 4.15.0-161-generic x86_64)

The apps are using Vapor 4.49.2 and 4.51.0. One server uses fluent and APNS while the other uses leaf and APNS.

I hope this helps

**Comment by 0xTim** [comment] 2021-11-03 18:49
Where are you logging to? When the app crashes you should get a stack trace saying way and hopefully some logs

**Comment by yousifKashef** [comment] 2021-11-04 07:20
The apps are run by Supervisor when the machine boots. Does it record stack traces and logs?

**Comment by fouadhatem** [comment] 2021-11-04 12:14
You'll need to figure out where your logs are on your installations and post them here. Check out the Supervisor documentation for how to do that: http://supervisord.org/logging.html

**Comment by 0xTim** [comment] 2021-11-17 14:47
Closing this as the main issue of finding logs has been resolved. Feel free to reopen if the crash is a Vapor issue!

**Closed by 0xTim** 2021-11-17 14:47 UTC
Labels: bug
