### ISSUE TITLE
Square brackets in query parameters

### ISSUE THREAD

**Issue by RussBaz** [vapor/vapor#2950] opened 2023-02-03 10:54 UTC
If I send a request with the following query parameters:

`?a[]=1&a[]=2`

I get:

`key: "a", value: ["1", "2"]`

However, if I send `?a[b]=1&a[b]=2`

I get `key: "a", value: []`

Replacing `[` and `]` with `%5B` and `%5D` makes no difference.

Furthermore, `?a[b]c=1` results in an exception `"Malformed form-urlencoded key encountered: a[b]c"`

1. Can you clarify if this is an intended behaviour?

I personally would like to parse `?a[b]=1&a[b]=2&a[c]=3` into
```
key: "a[b]", value ["1", "2"]
key: "a[c]", value: ["3"]
```

2. Is there a way to achieve what I want?

Here is the test Content struct:
```swift
struct RandomFilter: Content {
    private struct DynamicCodingKeys: CodingKey {
        var stringValue: String
        
        init?(stringValue: String) {
            self.stringValue = stringValue
        }
        
        var intValue: Int?
        
        init?(intValue: Int) {
            return nil
        }
    }
    
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: DynamicCodingKeys.self)
        
        for key in container.allKeys {
            let value = try container.decode([String].self, forKey: key)
            
            print("key: \"\(key.stringValue)\", value: \(value)")
        }
    }
}
```

Thank you.

**Comment by 0xTim** [comment] 2023-04-11 15:04
I don't think there's a way to achieve what you want and this is probably expected behaviour. Since `[` and `%5B` are effectively the same thing when it comes to a query parameters there's no way for us to 'escape' the bracket so we need to treat `a[b]` as a dictionary with a key rather than the key itself. Dictionaries are a pain in URL queries so Vapor needs to make a decision somewhere and this is the line we've drawn unfortunately.

I'll close this but feel free to ask more questions or reopen if you think there's a better solution

**Closed by 0xTim** 2023-04-11 15:04 UTC
Labels: enhancement
