### ISSUE TITLE
localization

### ISSUE THREAD

**Issue by Igor-Palaguta** [vapor/vapor#1105] opened 2017-08-07 21:36 UTC
* Vapor Version: 2

### Expected Behavior

Should support localization in similar way as it was in Vapor 1

**Comment by mono0926** [comment] 2017-08-17 01:04
Are there no ways to localize at Vapor 2?

**Comment by miroslavkovac** [comment] 2017-08-17 16:17
I am finalizing a full localization framework written in Swift with support for all locales, including custom language specific pluralization rules and string interpolation. It is easily integrated into Vapor, I hope I will be able to finish everything during the upcoming weekend.

**Comment by mono0926** [comment] 2017-08-18 02:27
@miroslavkovac 

Oh, I'm looking forward to it 😋

**Comment by miroslavkovac** [comment] 2017-08-19 18:31
@mono0926 here it is: https://github.com/miroslavkovac/Lingo.

Enjoy! :)

**Comment by mono0926** [comment] 2017-08-20 02:36
@miroslavkovac 

Thank you, it seems to be great 👍 
I'll use it!

**Comment by miroslavkovac** [comment] 2017-08-28 21:01
I have just finished with the Vapor Provider for Lingo and transferred it to vapor-community. It can be found here: https://github.com/vapor-community/Lingo-Provider.

**Comment by joeblau** [comment] 2017-11-04 11:34
Thanks so much!  Localization was the regression that prevented me from upgrading to vapor 2.x

**Comment by MrLotU** [comment] 2019-02-16 13:52
With this issue being originally targeted towards Vapor 2,Vapor 2 no longer being supported supported since November 2018, and a workable solution being https://github.com/vapor-community/Lingo-Provider, I will close this issue

[Version support](https://docs.vapor.codes/3.0/version/support/)

**Closed by MrLotU** 2019-02-16 13:52 UTC
Labels: enhancement
