### ISSUE TITLE
Add DateEncodingStrategy for url-encodedform

### ISSUE THREAD

**Issue by patrickbdev** [vapor/vapor#2221] opened 2020-03-03 23:25 UTC
Similar to JSONEncoder, it'd be useful to be able to set the decoding strategy:

```
case deferredToDate
case iso8601
case formatted(DateFormatter)
case custom((Date, Encoder) throws -> Void)
case millisecondsSince1970
case secondsSince1970
```

**Comment by jshier** [comment] 2020-03-07 21:03
You can [use Alamofire's](https://github.com/Alamofire/Alamofire/blob/master/Source/URLEncodedFormEncoder.swift#L109) since we cobbled together our encoder from Vapor's and other encoders.

**Comment by patrickbdev** [comment] 2020-03-07 22:39
Thanks @jshier, excellent suggestion

**Comment by tanner0101** [comment] 2020-04-02 17:08
Duplicate of https://github.com/vapor/vapor/issues/2133

**Closed by tanner0101** 2020-04-02 17:08 UTC
Labels: enhancement
