### ISSUE TITLE
Vapor not closing down properly

### ISSUE THREAD

**Issue by baxtercr** [vapor/vapor#569] opened 2016-09-04 14:47 UTC
Ctrl C on the mac is not shutting down the server properly.

Please see screenshot for sequence of events.

Mac OSX El Capitan.  
DEVELOPMENT-SNAPSHOT-2016-08-18-a
Vapor Toolbox v0.10.0
Vapor Framework v0.17.0

using default project created using vapour new. 

![screen shot 2016-09-04 at 15 42 24](https://cloud.githubusercontent.com/assets/139218/18231629/5a8ff19a-72b6-11e6-825a-ee8b02f67947.png)

I've had to kill the process before I can restart

**Comment by tannernelson** [comment] 2016-09-05 14:47
Duplicate of vapor/toolbox#68

**Closed by tannernelson** 2016-09-05 14:47 UTC
