### ISSUE TITLE
Multiple JWT signers not working as expected

### ISSUE THREAD

**Issue by Samsv77** [vapor/vapor#3031] opened 2023-06-26 17:32 UTC
Hello,
I am building an app that accepts 2 different JWTs for authentication, 1 that is generated by the app itself, 1 that is generated by an external entity.
As a result I am using 2 signers,

```
app.jwt.signers.use(.hs256(key: authSecret))    // For local app auth 
app.jwt.signers.use(.es256(key: .public(pem: ecdsaPublicKey))   // For external entity JWT auth
```

Per Vapor doc it should work, my app should accept either JWT and authenticate
But in reality it is only using the 1st signer, or whichever is set to default. If the 1st signer fail to validate the JWT, authentication fails with the error: `signature verification failed`
If I declare the ECDSA signer 1st, I can only validate JWTs with this signer, other JWTs will fail with the error `signature verification failed`

**Is it a bug or expected behavior ?**
If expected behavior, how can I accept 2 different JWTs ?

Note: I also tried with kid, but this expects the external entity to generate a JWT with the kid as well.
Expected behavior

Vapor should loop through the signers and verify the JWT.
Authentication should succeed if any of the signer is able to verify the JWT, and fail only if none of the signers can verify.

**Environment**

    Vapor Framework version: 4.67.3 - 4.77.0
    JWT version: 4.2.1

**Comment by 0xTim** [comment] 2023-07-05 11:57
Closing as a dupe of https://github.com/vapor/jwt/issues/147

**Closed by 0xTim** 2023-07-05 11:57 UTC
