### ISSUE TITLE
Throwing vs returning an error response (Vapor 3)

### ISSUE THREAD

**Issue by bygri** [vapor/vapor#1254] opened 2017-11-16 21:01 UTC
In the [documentation](https://docs.vapor.codes/3.0/getting-started/json/#encoding-an-error-response) for Vapor 3, a set of `Codable` these example request/response/error structs are presented:

```swift
/// A Login request (input)
/// Requires an email address and a password
struct LoginRequest: Decodable {
  var email: String
  var password: String
}

/// A login response (success output)
struct LoginResponse: Encodable, ResponseRepresentable {
  var token: String

  // The profile will be encoded to JSON
  var user: User.Profile
}

/// A login error (unsuccessful output)
struct LoginError: Encodable, ResponseRepresentable {
  // The reason will be represented in JSON as a `String`
  enum Reason: String, Encodable {
    case invalidCredentials
    case accountSuspended
  }

  var reason: Reason
}
```

The request is decoded, processed, and then a successful response is encoded and returned.

In case of error, the recommendation is to return `LoginError`:

`return LoginError(reason: .invalidCredentials)`

It seems un-Swifty to me to ever `return` an error when we have `throw` instead.

Ideally a throwable, returnable error would be able to set its own status code:

```swift
struct LoginError: Encodable, ErrorResponseRepresentable {
  enum Reason: String, Encodable {
    case invalidCredentials
    case accountSuspended
  }
  let status: .unauthorized
  var reason: Reason
}
```

**Comment by tanner0101** [comment] 2017-11-20 17:15
That part specifically has been removed. Keeping this open as a reminder to add a part about how to properly throw errors.

**Comment by tanner0101** [comment] 2018-04-27 01:33
Closing here since this issue is related to docs. 

The answer to the problem is to use `AbortError` in case anyone stumbles upon this issue in the future.

**Closed by tanner0101** 2018-04-27 01:33 UTC
Labels: enhancement
