### ISSUE TITLE
Make number of threads in app.threadPool configurable

### ISSUE THREAD

**Issue by devnikkin** [vapor/vapor#2308] opened 2020-04-11 09:56 UTC
The Vapor 4.0 documentation of "[Async](https://docs.vapor.codes/4.0/async/#blocking)" suggest to run any blocking work in the background, such that several clients won't block each other. I've set up a new project from scratch and registered two routes:

```swift
app.get("hello-again") { req -> String in
    print("hello-again requested")

    return "Hello, world, again!"
}
```
```swift
app.get("hello") { req -> EventLoopFuture<String> in
    print("hello requested")
    let promise = req.eventLoop.makePromise(of: Void.self)

    req.application.threadPool.submit { _ in
        sleep(5)
        print("(did some work)")

        promise.succeed(Void())
    }

    return promise.futureResult.transform(to: "Hello, world!")
}
```

If I request `GET/hello` and immediately `GET/hello-again`,  `GET/hello-again` is served directly as expected. But if I request `GET/hello` and than immediately a second `GET/hello`, the second request waits for the first one to complete. Thus, the output in my console is:

```
[ INFO ] GET /hello
hello requested
(did some work)
[ INFO ] GET /hello
hello requested
(did some work)
```

But from the documentation I would have rather expected:

```
[ INFO ] GET /hello
hello requested
[ INFO ] GET /hello
hello requested
(did some work)
(did some work)
```

What am I missing?

**Comment by t089** [comment] 2020-04-11 23:14
The answer to your question is that surprisingly the default size of the thread pool is one.

**Comment by t089** [comment] 2020-04-12 07:10
The relevant line is in `Sources/Vapor/Core/Core.swift`

**Comment by devnikkin** [comment] 2020-04-12 07:38
Thanks for your help! What would be the most idiomatic approach to increase the thread pool size? I'm wondering because `threadPool` is get-only and `Application` itself is marked as final, which prevents the class being overridden/inherited. 🤔

**Comment by t089** [comment] 2020-04-12 11:30
Yes I guess your right, seems like there is no way to customize this pool. I’m curious why this pool has only one thread? Seems rather useless for heavy traffic, especially since it it also used for file IO.

I would recommend you use our own thread pool and create it with a reasonable number of threads that fits your expected concurrency requirements.  Or, you can also use Dispatch to offload work from the eventloop. However, Dispatch also has an undocumented? upper limit of threads.

**Comment by tanner0101** [comment] 2020-04-14 14:40
The number of threads in the pool should be configurable. I'm not sure that `1` is an unreasonable default, though. We use `System.coreCount` (aka, use all the threads) for the number of event loops by default. This means any threads given to the thread pool are going to be competing with event loop threads for system time.

**Comment by 0xTim** [comment] 2020-04-14 14:41
This is deliberate essentially to stop your app being DDOSed. Because of the way event loops and threads work, they're generally tied to your system cores. So if you have one thread that is assigned to the blocking thread pool, any blocking work can go on the thread and your app will churn through it, leaving other threads to handle requests. 

So let's say you create a blocking thread pool with the same number of threads as your system. An attacker could send multiple simultaneous requests to an endpoint that uses the blocking thread and your machine will be blocked handling all that work and won't be able to handle any requests. Does that make sense?

**Comment by t089** [comment] 2020-04-14 15:30
Well, yes and no: if you have 4 cores, 4 eventloops and 16 additional threads in a pool, that means that you can have 16 concurrent blocking tasks on the background threads that will compete for cpu time with the event loop threads. The OS will make sure that every thread gets cpu time, of course thing will become slow when all threads are busy, but they won’t stop the world.

**Comment by tanner0101** [comment] 2020-04-14 17:49
@t089 good point. We discussed this a bit in Discord, too, and it was mentioned there that thread priority could have an impact here. If NIO's EventLoop threads were created with high priority then we wouldn't have to worry as much about thread pool threads competing for CPU time. It seems NIO is not doing that yet though. So I wonder if there is value in keeping the default thread pool size small to limit competition? A potential problem with only using one background thread is that blocking work will be unevenly competing with a single event loop's thread. Maybe using `System.coreCount` in both places is the best call.

**Comment by devnikkin** [comment] 2020-04-14 18:31
To be honest, I'm not yet used to Vapor or SSS at all. So please excuse me, if my following question seems odd 😄 

Suppose we have 4 cores, thus 4 event loops (EV) . If we make the first request, it's handled by our first event loop. The second request by the second loop, and so on. 

1st EV | 2nd EV | 3rd EV | 4th EV
------------ | ------------- | ------------- | -------------
first request (GET/hello) | / | / | / |
/ | second request (GET/hello-again) | / | / |

However, if we make two concurrent requests to the same route, they are handled by the same event loop because of the additional thread pools.

1st EV | 2nd EV | 3rd EV | 4th EV
------------ | ------------- | ------------- | -------------
first request (GET/hello) | / | / | / |
second request (GET/hello) | / | / | / |

So, why do we need the thread pools at all? Wouldn't it be more efficient to handle the second (concurrent) request by the next event loop in a round-robin fashion?

**Comment by tanner0101** [comment] 2020-04-14 18:37
If you make two requests (even at the same exact time) they will go to separate event loops. It works round-robin like you mentioned. The thread pool is for executing CPU or I/O bound (blocking) work. That way you avoid blocking the event loops since a single loop may be handling hundreds or thousands of requests at a given moment.

**Comment by devnikkin** [comment] 2020-04-14 20:05
Cannot confirm so far 🤔

I've added 
```swift
print(req.eventLoop.description)
```
to both routes above, and called `GET /hello`, `GET /hello` and `GET /hello-again` almost at the same time. But the event loop descriptions of the two `GET /hello` requests are identical.

```
[ INFO ] GET /hello
hello requested
SelectableEventLoop { selector = Selector { descriptor = 8 }, thread = NIOThread(name = NIO-ELT-0-#5) }
[ INFO ] GET /hello-again
hello-again requested
SelectableEventLoop { selector = Selector { descriptor = 9 }, thread = NIOThread(name = NIO-ELT-0-#6) }
(did some work)
[ INFO ] GET /hello
hello requested
SelectableEventLoop { selector = Selector { descriptor = 8 }, thread = NIOThread(name = NIO-ELT-0-#5) }
(did some work)
```

**Comment by t089** [comment] 2020-04-14 21:35
There a few things to unpack here (i think most of it is clear, but just to be safe let me say it how I understood it): the trick about NIO and the event loops is that all network calls are non-blocking, thus waiting for a network call does not block the current thread, so it can continue working on the next request while the first one is waiting for a DB call for example. This allows nio to support many, many concurrent requests even with a single thread. 

If you have some task that requires blocking IO you must move this off the event loop. Because if you blocked the event loop thread you could not handle new requests. If you move the blocking IO to a thread pool of size 1, this means that your app can only ever execute one blocking IO operation at the same time. This can be quite some bottleneck. In the case of NIO and vapor the blocking IO is mostly file system operations. So let’s imagine you provide some way to download a large file from the filesystem, which will take several minutes. During this time, the single thread pool thread will be blocked (but not consuming much CPU time, because it mostly waits for IO). During this time no other request will be able to access the file system (css files, html templates, etc), because this single thread is still handling the download. That’s why I think you should be able to size the pool in a way that makes sense for the requirements of your app. If you want to enable 32 concurrent downloads the thread pool should be of size 32, for example. Am I missing something?

If your tasks are mostly CPU bound, eg some video transcoding, you could say it does not make sense to allow more than core count threads, because the CPU won’t be able to work on more tasks at the same time. But then if you are already working on 4 very long transcodings, if a 5th one comes in, it has to wait for the one of the others to finish before it can start. But if the 5th one is actually very short it would be much better to share the CPU time with the others tasks so that it can be processed in parallel and finish while the other tasks are still ongoing. So even in this case I would argue that a larger thread pool would be better.

**Comment by tanner0101** [comment] 2020-04-16 15:56
@t089 

> There a few things to unpack here (i think most of it is clear, but just to be safe let me say it how I understood it)

Yup, that's exactly how it works 👍 

> So even in this case I would argue that a larger thread pool would be better.

Yeah this conversation has convinced me. Initially the idea for the thread pool was mostly around asynchronous password hashing, i.e., CPU bound work. This made me think that we want to limit the amount of competition for CPU resources by creating a smaller thread pool. But the better way to workaround this is to tell the scheduler to prioritize EventLoop threads over background threads. Limiting the amount of background work to only one thing at a time is a bad tradeoff. 

That said, what would be a better default? Should we use something like `System.coreCount` (cpu cores * hyperthreads) or a reasonable static number like `32` / `64`?

**Comment by t089** [comment] 2020-04-16 16:26
If I remember correctly libdispatch uses 64.

**Comment by gwynne** [comment] 2021-01-27 08:07
I'd like to implement this, finally - but I'm concerned that changing the default behavior of the thread pool at this point could expose previously-hidden concurrency bugs in common uses of the thread pool; these semantics are not exactly obvious unless you've made at least some study of the topic, and AFAIK we don't really document how to deal with the matter. Is there some way to get a sense of just _how_ breaking it might be to change the default?

(Making the value configurable is a no-brainer, at least - there's no danger of breakage in that by itself.)

**Comment by gwynne** [comment] 2021-01-27 08:09
cc @0xTim @tanner0101 @siemensikkema @weissi @Lukasa - would very much like some input on this.

**Comment by 0xTim** [comment] 2021-01-27 08:25
Vapor's approach to semantic versioning has always been a bit 'lax' within the restrictions of Swift and I'd be happy changing the default number of threads in the pool in a minor update since that's certainly isn't a strictly semver major change.

If we do go down the route then we should definitely document it somewhere. Are you concerned about rejoining of work split out across different threads or other bugs?

**Comment by madsodgaard** [comment] 2021-01-27 08:33
At least adding a configurable option and adding a message in the docs about the *"optimal"* default would be nice.

I don't fully grasp the consequences increasing the default thread pool would have in terms of existing uses. But I could imagine a large portion of uses of the thread pool the is the asynchronous password hasher included with Vapor.

**Comment by siemensikkema** [comment] 2021-01-27 08:33
@gwynne Of the people tagged I am by far the least knowledgeable on the subject but I can at least share my opinion on your concerns of exposing previously hidden bugs. 

Sure, the safest way would be to make it configurable but keep the default at 1. But I think the current behavior is confusing (a pool of 1 is not much of a pool, is it?) as evidenced by this issue. So I think we should also use a default >1. Any issues that _do_ arise are technically the result of bugs that have been there all along anyway, just invisible and can be remedied quite easily by setting the pool size to 1 again.

**Comment by Lukasa** [comment] 2021-01-27 10:24
There is no specific semver issue with changing the default size of the thread pool. While it may expose bugs, those bugs were always latent in the program. Exposing them isn't great, but it's not the end of the world.

Raising the default pool size seems reasonable.

- - -

Apropos of nothing, but the above-discussed behaviour of request scheduling on event loops is not accurate. Different _requests_ are not round-robined on event loops, different _connections_ are. HTTP clients can and do send multiple requests on a single connection, and all such requests will be delivered to the same event loop.

Let's also talk about thread priorities briefly, as they were mentioned in this conversation. NIO does not use POSIX thread priorities today because it's inappropriate for a library to do so on its own. If we did, we'd risk creating priority inversions in your applications where our event loop threads starve your other work, or where they themselves are starved by things you don't need as urgently. Such bugs are subtle and only manifest in high-load scenarios where they appear as drastic performance degradation and timeouts, making them fiendishly hard to debug and root-cause. Thread priorities are not a hammer you can hit your program with to make it go fast.

The idea above (NIO should prioritise its event loops over its thread pools) is a good example of how this can lead you astray. This idea seems reasonable on its face, but has a hidden risk associated with backpressure. If your thread-pool tasks are not imposing backpressure on the system, and the NIO threads move faster than the thread pool, an active client can starve the thread pool entirely. If they can do so while enqueing more work onto the thread pool, they can cause the thread pool task queue to grow unbounded and DoS the program.

This can be carefully architected around using backpressure mechanisms such as token buckets, but it's a highly dangerous _default_ behaviour. In the opposite case (thread pool at higher priority than event loop) your I/O will naturally slow down as your thread pool gets busy. This has the effect of implicitly applying backpressure, as you literally accept work more slowly (or even not at all, in the case where you have the same number of pool threads as cores) as long as you're doing thread pool tasks. This is _also_ a DoS vector: if I can queue thread pool tasks I can force you to stop serving other users while you handle my work.

With all of the above mentioned, we should probably add hooks to allow users to configure the relative thread priorities of both NIO's event loops and its thread pool. This would allow experienced users to configure these as they see fit. However, the default should still be left as-is, to reduce the risk of a priority inversion rendering the system unavailable.

**Closed** 2021-06-09 08:26 UTC
Labels: enhancement

**Comment by mkll** [comment] 2021-09-23 05:14
Guys, it seems that there is a unintended side effect in the implementation of release 4.46.0.

Here is the story. I noticed that if I override the default `NIOThreadPool` size in `configure()`, then the Vapor application stops responding to restart signals and is killed by systemd. If I don't override, then everything is ok.

I decided to sort it out, set a few breakpoints and saw this:

Of course, the default `NIOThreadPool` is initialized first

![1](https://user-images.githubusercontent.com/1652009/134457408-0909dc26-b443-4ed2-8c94-912bc48638bb.png)

Then, an instance of `NonBlockingFileIO` is created with this default pool

![2](https://user-images.githubusercontent.com/1652009/134457422-ec9134c9-8ec5-43bb-8d15-1044e93fe660.png)

(invoked from here)

![3](https://user-images.githubusercontent.com/1652009/134457438-d9b82267-9949-4e4f-93f1-18942668f6fa.png)

And only then the default `NIOThreadPool` is redefined from `configure()`

![4](https://user-images.githubusercontent.com/1652009/134457444-b4f7d631-71b9-4d3f-92ea-497a663bd6c2.png)

(Btw, it's possible that at this point the `syncShutdownGracefully()` method terminates with error, because the first `NIOThreadPool` is still in use by `NonBlockingFileIO` instance)

What have we come to?

Well, after the initialization of the Vapor app, we have 2 instances of `NIOThreadPool`. The first one is referenced from the first `NonBlockingFileIO` instantiated, but **not** referenced from `app.threadPool` variable. Second one **is** referenced from `app.threadPool` variable and from subsequent `NonBlockingFileIO`'s, if any.

So, on application shutdown, the `syncShutdownGracefully()` method is not called on the first instance of `NIOThreadPool`, because it was orphaned and inaccessible.

Perhaps this is why the Vapor application cannot be shutdowned normally.

Your thoughts are very appreciated.

**Comment by 0xTim** [comment] 2021-09-23 09:31
The fix for this should be to initialise a new fileIO with the new thread pool so the original one doesn't get orphaned. Want to do a PR @mkll ?

**Comment by mkll** [comment] 2021-09-23 10:31
@0xTim As for me, this is a problem with the initialization sequence, which cannot be fixed without reordering the sequence, but the implementation of this reordering is not quite obvious to me.

Maybe creating a pool at once with the right number of threads is a better idea?

**Comment by 0xTim** [comment] 2021-09-23 10:46
That won't be possible because you can configure the number of threads before that app actually starts, but at that point the thread pool has already been created because the FileIO uses it to load the .env file etc.

There's no reordering needed, you just need to create a new `NonBlockingFileIO` when a new thread pool is created and switch it out

**Comment by mkll** [comment] 2021-09-23 13:02
> and switch it out

Not sure I got it right. If `fileio` were a stored variable, then such a switch would not be a problem, but `fileio` is a computed variable. I seem to be dumb, but I don't understand how the value of a computed variable can be replaced, because it doesn't have a setter, and we can't use the stored variable in the extension.

**Comment by fouadhatem** [comment] 2021-09-23 14:46
@mkll do you think #2502 is related?

**Comment by mkll** [comment] 2021-09-23 14:58
@fouadhatem Well, the symptoms are similar and it's tempting to say yes, but I'm afraid it's too early to jump to that conclusion.

Note that in that situation (https://github.com/vapor/vapor/issues/2502), an additional signal handler helped to fix it. In the current situation, however, it does not help. This may indicate that the causes are different, albeit similar at first glance.

**Comment by fouadhatem** [comment] 2021-09-23 15:13
@mkll the signal handler in #2502 seems to have fixed it for Linux, but the issue still persists for macOS on hardware with older configurations. I have a couple of  older MacBook Air's lying around that persistently show an error on shutdown. The only workaround is to disable debugging, and the issue goes away. Newer laptops with the exact same software (macOS, Xcode, basic Vapor app) show it randomly but not too often. Can't reliably reproduce.

I thought your issue might be related to #2502 because of the similar behavior, though now that I think of it, it seems that it might not be.

**Comment by 0xTim** [comment] 2021-09-27 12:25
@mkll you're right I misread the code. What I'm confused about now is that the `fileIO` is a computed property so you should get a new instance each time and it shouldn't hold in to the thread pool unless you're retaining the file IO somewhere?

**Comment by mkll** [comment] 2021-09-27 13:40
@0xTim Oh, thanks, I thought I misunderstood something.

> and it shouldn't hold in to the thread pool

Yes, I also do not understand why this is happening. But the result is reproducible 100% of the time.
