### ISSUE TITLE
vapor build fails with clang-10 error 

### ISSUE THREAD

**Issue by quantum-fusion** [vapor/vapor#2552] opened 2021-01-13 16:31 UTC
### Describe the bug

A downloaded vapor and built it with swift build, and it fails, due to clang-10 error, no such file or directory. 

---
swift build --verbose
/usr/bin/xcrun --sdk macosx --show-sdk-platform-path
/usr/bin/xcrun --sdk macosx --find xctest
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc -print-target-info
xcrun --sdk macosx --show-sdk-platform-path
xcrun vtool -show-build /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks/XCTest.framework/XCTest
xcrun --sdk iphoneos --show-sdk-platform-path
xcrun vtool -show-build /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Frameworks/XCTest.framework/XCTest
xcrun --sdk appletvos --show-sdk-platform-path
xcrun vtool -show-build /Applications/Xcode.app/Contents/Developer/Platforms/AppleTVOS.platform/Developer/Library/Frameworks/XCTest.framework/XCTest
xcrun --sdk watchos --show-sdk-platform-path
xcrun vtool -show-build /Applications/Xcode.app/Contents/Developer/Platforms/WatchOS.platform/Developer/Library/Frameworks/XCTest.framework/XCTest
/Users/hottelet/miniconda3/bin/x86_64-apple-darwin13.4.0-clang -fobjc-arc -target x86_64-apple-macosx10.10 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk -F /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks -g -O0 -DSWIFT_PACKAGE=1 -DDEBUG=1 -fblocks -index-store-path /Users/hottelet/vapor/.build/x86_64-apple-macosx/debug/index/store -fmodules -fmodule-name=CNIOBoringSSL -I /Users/hottelet/vapor/.build/checkouts/swift-nio-ssl/Sources/CNIOBoringSSL/include -fmodules-cache-path=/Users/hottelet/vapor/.build/x86_64-apple-macosx/debug/ModuleCache -MD -MT dependencies -MF /Users/hottelet/vapor/.build/x86_64-apple-macosx/debug/CNIOBoringSSL.build/ssl/tls13_server.cc.d -std=c++14 -c /Users/hottelet/vapor/.build/checkouts/swift-nio-ssl/Sources/CNIOBoringSSL/ssl/tls13_server.cc -o /Users/hottelet/vapor/.build/x86_64-apple-macosx/debug/CNIOBoringSSL.build/ssl/tls13_server.cc.o
/Users/hottelet/miniconda3/bin/x86_64-apple-darwin13.4.0-clang -fobjc-arc -target x86_64-apple-macosx10.10 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk -F /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks -g -O0 -DSWIFT_PACKAGE=1 -DDEBUG=1 -fblocks -index-store-path /Users/hottelet/vapor/.build/x86_64-apple-macosx/debug/index/store -fmodules -fmodule-name=CNIOBoringSSLShims -I /Users/hottelet/vapor/.build/checkouts/swift-nio-ssl/Sources/CNIOBoringSSLShims/include -I /Users/hottelet/vapor/.build/checkouts/swift-nio-ssl/Sources/CNIOBoringSSL/include -fmodule-map-file=/Users/hottelet/vapor/.build/x86_64-apple-macosx/debug/CNIOBoringSSL.build/module.modulemap -fmodules-cache-path=/Users/hottelet/vapor/.build/x86_64-apple-macosx/debug/ModuleCache -MD -MT dependencies -MF /Users/hottelet/vapor/.build/x86_64-apple-macosx/debug/CNIOBoringSSLShims.build/shims.c.d -c /Users/hottelet/vapor/.build/checkouts/swift-nio-ssl/Sources/CNIOBoringSSLShims/shims.c -o /Users/hottelet/vapor/.build/x86_64-apple-macosx/debug/CNIOBoringSSLShims.build/shims.c.o
/Users/hottelet/miniconda3/bin/x86_64-apple-darwin13.4.0-clang -fobjc-arc -target x86_64-apple-macosx10.10 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk -F /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks -g -O0 -DSWIFT_PACKAGE=1 -DDEBUG=1 -fblocks -index-store-path /Users/hottelet/vapor/.build/x86_64-apple-macosx/debug/index/store -fmodules -fmodule-name=CNIOLinux -I /Users/hottelet/vapor/.build/checkouts/swift-nio/Sources/CNIOLinux/include -fmodules-cache-path=/Users/hottelet/vapor/.build/x86_64-apple-macosx/debug/ModuleCache -MD -MT dependencies -MF /Users/hottelet/vapor/.build/x86_64-apple-macosx/debug/CNIOLinux.build/shim.c.d -c /Users/hottelet/vapor/.build/checkouts/swift-nio/Sources/CNIOLinux/shim.c -o /Users/hottelet/vapor/.build/x86_64-apple-macosx/debug/CNIOLinux.build/shim.c.o
/Users/hottelet/miniconda3/bin/x86_64-apple-darwin13.4.0-clang -fobjc-arc -target x86_64-apple-macosx10.10 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk -F /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks -g -O0 -DSWIFT_PACKAGE=1 -DDEBUG=1 -fblocks -index-store-path /Users/hottelet/vapor/.build/x86_64-apple-macosx/debug/index/store -fmodules -fmodule-name=CNIOSHA1 -I /Users/hottelet/vapor/.build/checkouts/swift-nio/Sources/CNIOSHA1/include -fmodules-cache-path=/Users/hottelet/vapor/.build/x86_64-apple-macosx/debug/ModuleCache -MD -MT dependencies -MF /Users/hottelet/vapor/.build/x86_64-apple-macosx/debug/CNIOSHA1.build/c_nio_sha1.c.d -c /Users/hottelet/vapor/.build/checkouts/swift-nio/Sources/CNIOSHA1/c_nio_sha1.c -o /Users/hottelet/vapor/.build/x86_64-apple-macosx/debug/CNIOSHA1.build/c_nio_sha1.c.o
/Users/hottelet/miniconda3/bin/x86_64-apple-darwin13.4.0-clang -fobjc-arc -target x86_64-apple-macosx10.10 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk -F /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks -g -O0 -DSWIFT_PACKAGE=1 -DDEBUG=1 -fblocks -index-store-path /Users/hottelet/vapor/.build/x86_64-apple-macosx/debug/index/store -fmodules -fmodule-name=CNIOBoringSSL -I /Users/hottelet/vapor/.build/checkouts/swift-nio-ssl/Sources/CNIOBoringSSL/include -fmodules-cache-path=/Users/hottelet/vapor/.build/x86_64-apple-macosx/debug/ModuleCache -MD -MT dependencies -MF /Users/hottelet/vapor/.build/x86_64-apple-macosx/debug/CNIOBoringSSL.build/ssl/tls_method.cc.d -std=c++14 -c /Users/hottelet/vapor/.build/checkouts/swift-nio-ssl/Sources/CNIOBoringSSL/ssl/tls_method.cc -o /Users/hottelet/vapor/.build/x86_64-apple-macosx/debug/CNIOBoringSSL.build/ssl/tls_method.cc.o
/Users/hottelet/miniconda3/bin/x86_64-apple-darwin13.4.0-clang -fobjc-arc -target x86_64-apple-macosx10.10 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk -F /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks -g -O0 -DSWIFT_PACKAGE=1 -DDEBUG=1 -fblocks -index-store-path /Users/hottelet/vapor/.build/x86_64-apple-macosx/debug/index/store -fmodules -fmodule-name=CNIOBoringSSL -I /Users/hottelet/vapor/.build/checkouts/swift-nio-ssl/Sources/CNIOBoringSSL/include -fmodules-cache-path=/Users/hottelet/vapor/.build/x86_64-apple-macosx/debug/ModuleCache -MD -MT dependencies -MF /Users/hottelet/vapor/.build/x86_64-apple-macosx/debug/CNIOBoringSSL.build/ssl/tls13_enc.cc.d -std=c++14 -c /Users/hottelet/vapor/.build/checkouts/swift-nio-ssl/Sources/CNIOBoringSSL/ssl/tls13_enc.cc -o /Users/hottelet/vapor/.build/x86_64-apple-macosx/debug/CNIOBoringSSL.build/ssl/tls13_enc.cc.o
/Users/hottelet/miniconda3/bin/x86_64-apple-darwin13.4.0-clang -fobjc-arc -target x86_64-apple-macosx10.10 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk -F /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks -g -O0 -DSWIFT_PACKAGE=1 -DDEBUG=1 -fblocks -index-store-path /Users/hottelet/vapor/.build/x86_64-apple-macosx/debug/index/store -fmodules -fmodule-name=CNIOWindows -I /Users/hottelet/vapor/.build/checkouts/swift-nio/Sources/CNIOWindows/include -fmodules-cache-path=/Users/hottelet/vapor/.build/x86_64-apple-macosx/debug/ModuleCache -MD -MT dependencies -MF /Users/hottelet/vapor/.build/x86_64-apple-macosx/debug/CNIOWindows.build/shim.c.d -c /Users/hottelet/vapor/.build/checkouts/swift-nio/Sources/CNIOWindows/shim.c -o /Users/hottelet/vapor/.build/x86_64-apple-macosx/debug/CNIOWindows.build/shim.c.o
/Users/hottelet/miniconda3/bin/x86_64-apple-darwin13.4.0-clang -fobjc-arc -target x86_64-apple-macosx10.10 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk -F /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks -g -O0 -DSWIFT_PACKAGE=1 -DDEBUG=1 -fblocks -index-store-path /Users/hottelet/vapor/.build/x86_64-apple-macosx/debug/index/store -fmodules -fmodule-name=CNIOWindows -I /Users/hottelet/vapor/.build/checkouts/swift-nio/Sources/CNIOWindows/include -fmodules-cache-path=/Users/hottelet/vapor/.build/x86_64-apple-macosx/debug/ModuleCache -MD -MT dependencies -MF /Users/hottelet/vapor/.build/x86_64-apple-macosx/debug/CNIOWindows.build/WSAStartup.c.d -c /Users/hottelet/vapor/.build/checkouts/swift-nio/Sources/CNIOWindows/WSAStartup.c -o /Users/hottelet/vapor/.build/x86_64-apple-macosx/debug/CNIOWindows.build/WSAStartup.c.o
/Users/hottelet/miniconda3/bin/x86_64-apple-darwin13.4.0-clang -fobjc-arc -target x86_64-apple-macosx10.10 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk -F /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks -g -O0 -DSWIFT_PACKAGE=1 -DDEBUG=1 -fblocks -index-store-path /Users/hottelet/vapor/.build/x86_64-apple-macosx/debug/index/store -fmodules -fmodule-name=CNIOHTTPParser -I /Users/hottelet/vapor/.build/checkouts/swift-nio/Sources/CNIOHTTPParser/include -fmodules-cache-path=/Users/hottelet/vapor/.build/x86_64-apple-macosx/debug/ModuleCache -MD -MT dependencies -MF /Users/hottelet/vapor/.build/x86_64-apple-macosx/debug/CNIOHTTPParser.build/c_nio_http_parser.c.d -c /Users/hottelet/vapor/.build/checkouts/swift-nio/Sources/CNIOHTTPParser/c_nio_http_parser.c -o /Users/hottelet/vapor/.build/x86_64-apple-macosx/debug/CNIOHTTPParser.build/c_nio_http_parser.c.o
/Users/hottelet/miniconda3/bin/x86_64-apple-darwin13.4.0-clang -fobjc-arc -target x86_64-apple-macosx10.10 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk -F /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks -g -O0 -DSWIFT_PACKAGE=1 -DDEBUG=1 -fblocks -index-store-path /Users/hottelet/vapor/.build/x86_64-apple-macosx/debug/index/store -fmodules -fmodule-name=CNIODarwin -I /Users/hottelet/vapor/.build/checkouts/swift-nio/Sources/CNIODarwin/include -fmodules-cache-path=/Users/hottelet/vapor/.build/x86_64-apple-macosx/debug/ModuleCache -MD -MT dependencies -MF /Users/hottelet/vapor/.build/x86_64-apple-macosx/debug/CNIODarwin.build/shim.c.d -c /Users/hottelet/vapor/.build/checkouts/swift-nio/Sources/CNIODarwin/shim.c -o /Users/hottelet/vapor/.build/x86_64-apple-macosx/debug/CNIODarwin.build/shim.c.o
/Users/hottelet/miniconda3/bin/x86_64-apple-darwin13.4.0-clang -fobjc-arc -target x86_64-apple-macosx10.10 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk -F /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks -g -O0 -DSWIFT_PACKAGE=1 -DDEBUG=1 -fblocks -index-store-path /Users/hottelet/vapor/.build/x86_64-apple-macosx/debug/index/store -fmodules -fmodule-name=CNIOBoringSSL -I /Users/hottelet/vapor/.build/checkouts/swift-nio-ssl/Sources/CNIOBoringSSL/include -fmodules-cache-path=/Users/hottelet/vapor/.build/x86_64-apple-macosx/debug/ModuleCache -MD -MT dependencies -MF /Users/hottelet/vapor/.build/x86_64-apple-macosx/debug/CNIOBoringSSL.build/ssl/tls13_client.cc.d -std=c++14 -c /Users/hottelet/vapor/.build/checkouts/swift-nio-ssl/Sources/CNIOBoringSSL/ssl/tls13_client.cc -o /Users/hottelet/vapor/.build/x86_64-apple-macosx/debug/CNIOBoringSSL.build/ssl/tls13_client.cc.o
/Users/hottelet/miniconda3/bin/x86_64-apple-darwin13.4.0-clang -fobjc-arc -target x86_64-apple-macosx10.10 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk -F /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks -g -O0 -DSWIFT_PACKAGE=1 -DDEBUG=1 -fblocks -index-store-path /Users/hottelet/vapor/.build/x86_64-apple-macosx/debug/index/store -fmodules -fmodule-name=CNIOBoringSSL -I /Users/hottelet/vapor/.build/checkouts/swift-nio-ssl/Sources/CNIOBoringSSL/include -fmodules-cache-path=/Users/hottelet/vapor/.build/x86_64-apple-macosx/debug/ModuleCache -MD -MT dependencies -MF /Users/hottelet/vapor/.build/x86_64-apple-macosx/debug/CNIOBoringSSL.build/ssl/tls13_both.cc.d -std=c++14 -c /Users/hottelet/vapor/.build/checkouts/swift-nio-ssl/Sources/CNIOBoringSSL/ssl/tls13_both.cc -o /Users/hottelet/vapor/.build/x86_64-apple-macosx/debug/CNIOBoringSSL.build/ssl/tls13_both.cc.o
/Users/hottelet/miniconda3/bin/x86_64-apple-darwin13.4.0-clang -fobjc-arc -target x86_64-apple-macosx10.10 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk -F /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks -g -O0 -DSWIFT_PACKAGE=1 -DDEBUG=1 -fblocks -index-store-path /Users/hottelet/vapor/.build/x86_64-apple-macosx/debug/index/store -fmodules -fmodule-name=CNIOBoringSSL -I /Users/hottelet/vapor/.build/checkouts/swift-nio-ssl/Sources/CNIOBoringSSL/include -fmodules-cache-path=/Users/hottelet/vapor/.build/x86_64-apple-macosx/debug/ModuleCache -MD -MT dependencies -MF /Users/hottelet/vapor/.build/x86_64-apple-macosx/debug/CNIOBoringSSL.build/ssl/tls_record.cc.d -std=c++14 -c /Users/hottelet/vapor/.build/checkouts/swift-nio-ssl/Sources/CNIOBoringSSL/ssl/tls_record.cc -o /Users/hottelet/vapor/.build/x86_64-apple-macosx/debug/CNIOBoringSSL.build/ssl/tls_record.cc.o
/Users/hottelet/miniconda3/bin/x86_64-apple-darwin13.4.0-clang -fobjc-arc -target x86_64-apple-macosx10.10 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk -F /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks -g -O0 -DSWIFT_PACKAGE=1 -DDEBUG=1 -fblocks -index-store-path /Users/hottelet/vapor/.build/x86_64-apple-macosx/debug/index/store -fmodules -fmodule-name=CNIOBoringSSL -I /Users/hottelet/vapor/.build/checkouts/swift-nio-ssl/Sources/CNIOBoringSSL/include -fmodules-cache-path=/Users/hottelet/vapor/.build/x86_64-apple-macosx/debug/ModuleCache -MD -MT dependencies -MF /Users/hottelet/vapor/.build/x86_64-apple-macosx/debug/CNIOBoringSSL.build/ssl/t1_lib.cc.d -std=c++14 -c /Users/hottelet/vapor/.build/checkouts/swift-nio-ssl/Sources/CNIOBoringSSL/ssl/t1_lib.cc -o /Users/hottelet/vapor/.build/x86_64-apple-macosx/debug/CNIOBoringSSL.build/ssl/t1_lib.cc.o
/Users/hottelet/miniconda3/bin/x86_64-apple-darwin13.4.0-clang -fobjc-arc -target x86_64-apple-macosx10.10 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk -F /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks -g -O0 -DSWIFT_PACKAGE=1 -DDEBUG=1 -fblocks -index-store-path /Users/hottelet/vapor/.build/x86_64-apple-macosx/debug/index/store -fmodules -fmodule-name=CNIOBoringSSL -I /Users/hottelet/vapor/.build/checkouts/swift-nio-ssl/Sources/CNIOBoringSSL/include -fmodules-cache-path=/Users/hottelet/vapor/.build/x86_64-apple-macosx/debug/ModuleCache -MD -MT dependencies -MF /Users/hottelet/vapor/.build/x86_64-apple-macosx/debug/CNIOBoringSSL.build/ssl/t1_enc.cc.d -std=c++14 -c /Users/hottelet/vapor/.build/checkouts/swift-nio-ssl/Sources/CNIOBoringSSL/ssl/t1_enc.cc -o /Users/hottelet/vapor/.build/x86_64-apple-macosx/debug/CNIOBoringSSL.build/ssl/t1_enc.cc.o
/Users/hottelet/miniconda3/bin/x86_64-apple-darwin13.4.0-clang -fobjc-arc -target x86_64-apple-macosx10.10 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk -F /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks -g -O0 -DSWIFT_PACKAGE=1 -DDEBUG=1 -fblocks -index-store-path /Users/hottelet/vapor/.build/x86_64-apple-macosx/debug/index/store -fmodules -fmodule-name=CNIOBoringSSL -I /Users/hottelet/vapor/.build/checkouts/swift-nio-ssl/Sources/CNIOBoringSSL/include -fmodules-cache-path=/Users/hottelet/vapor/.build/x86_64-apple-macosx/debug/ModuleCache -MD -MT dependencies -MF /Users/hottelet/vapor/.build/x86_64-apple-macosx/debug/CNIOBoringSSL.build/ssl/ssl_x509.cc.d -std=c++14 -c /Users/hottelet/vapor/.build/checkouts/swift-nio-ssl/Sources/CNIOBoringSSL/ssl/ssl_x509.cc -o /Users/hottelet/vapor/.build/x86_64-apple-macosx/debug/CNIOBoringSSL.build/ssl/ssl_x509.cc.o
clang-10: error: unknown argument: '-index-store-path'
clang-10: error: unknown argument: '-index-store-path'
clang-10: error: unknown argument: '-index-store-path'
clang-10: error: unknown argument: '-index-store-path'
clang-10: error: no such file or directory: '/Users/hottelet/vapor/.build/x86_64-apple-macosx/debug/index/store'
clang-10: error: no such file or directory: '/Users/hottelet/vapor/.build/x86_64-apple-macosx/debug/index/store'
clang-10: error: no such file or directory: '/Users/hottelet/vapor/.build/x86_64-apple-macosx/debug/index/store'
clang-10: error: no such file or directory: '/Users/hottelet/vapor/.build/x86_64-apple-macosx/debug/index/store'
clang-10: error: unknown argument: '-index-store-path'

**Comment by 0xTim** [comment] 2021-03-05 21:40
This is a problem with your installed Swift version and nothing to do with Vapor. If you build any swift package you'll have the same error right?

**Comment by quantum-fusion** [comment] 2021-03-07 14:09
@0xTim We decided to downgrade the version of Swift, due to a a bug, and I am not sure where this leaves us.

swift --version
Apple Swift version 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28)
Target: x86_64-apple-darwin20.4.0

**Comment by 0xTim** [comment] 2021-03-11 14:09
@quantum-fusion downgrade from what to what?

**Comment by quantum-fusion** [comment] 2021-03-11 14:38
@0xTim You wanted swift 5.3.2 because you reported that swift had a bug with the latest version of vapor4. I have no idea how to proceed here, because the project of interest was supporting vapor3, and the project owner has not wished to upgrade his code.  I found a second project example here of how to host a COREML model with vapor, but i am afraid to report it is several years old (https://github.com/KVTaniguchi/KVCoreML), and (https://github.com/rickwierenga/heartbeat-tutorials/issues/3).  My best recommendation is that an example for hosting a CoreML model with vapor4, because I don't see a good candidate example.  I don't think we need to re-invent the wheel here, but I am no vapor expert, and all of these dependencies are a complete unknown to me, since I don't have a workable example, I have to assume that we are broken in development, since it hasn't been tested yet. I see no proof of that.

**Comment by fouadhatem** [comment] 2021-03-11 16:29
@quantum-fusion if you try to build any other Swift package (not Vapor), do you get the same error? 

Try creating a brand new non-Vapor Swift package, build it and see if you get the same error.

On a side note: your bug report thread seems to have a broken flow. Did you delete any parts of the conversation? Doing so makes it harder to follow along for those attempting to help.

**Comment by quantum-fusion** [comment] 2021-03-11 20:11
@fouadhatem I believe the issue is that the project located here (https://github.com/rickwierenga/heartbeat-tutorials/tree/master/CoreML-API), supports vapor3 which had at one time ssl dependency issues.  Tim points out that in vapor4 the ssl dependencies have been eliminated, and I don't know what the workaround might be, other than to say that the project is a vapor3 project that will not compile. The current version of swift I am using is 5.3.2 and I selected that one, because Tim reported that it is a requirement for vapor4.  I do not know what the Xcode version requirement was for vapor3, nor do I know if it currently builds successfully.  If you wanted to see the flow of what happened with a vapor3 project you can see here (https://github.com/rickwierenga/heartbeat-tutorials/issues/3).  I don't know how to proceed on this, and the original developer does not seem to want to help upgrade to vapor4, so I don't know if this path will work for vapor3 anymore since the Big Sur upgrade.

**Comment by 0xTim** [comment] 2021-03-31 10:02
I'm closing this as this the issue is to do with Xcode and Swift and not Vapor

**Closed by 0xTim** 2021-03-31 10:02 UTC
Labels: bug
