### ISSUE TITLE
Missing iOS check

### ISSUE THREAD

**Issue by grosch** [vapor/vapor#2146] opened 2020-01-10 19:11 UTC
https://github.com/vapor/vapor/blob/adcce86be49463445a5b24c1bc3f0532b21ab845/Sources/Vapor/Content/ContentConfiguration.swift#L33

https://github.com/vapor/vapor/blob/adcce86be49463445a5b24c1bc3f0532b21ab845/Sources/Vapor/Utilities/Thread.swift#L4

Those need to also have an iOS 10 check.  I'm not giving a pull request here because I'm not 100% sure this is how it's supposed to work.

**Comment by maxbritto** [comment] 2020-02-17 15:44
Indeed, with the latest beta, new projects fail to build because of this error

**Comment by tanner0101** [comment] 2020-02-17 20:30
The latest betas should specify macOS 10.14 and later as the only supported platforms: https://github.com/vapor/vapor/blob/master/Package.swift#L6-L8

Xcode should not compile the package unless those requirements are met.

**Comment by maxbritto** [comment] 2020-02-17 22:26
It was a vanilla new project generated from the command line tool using 3.19 beta.
I've updated to the latest beta (3.21) and it now builds without issue even though I don't see in the latests releases what would have fixed it. XCode still allows me to choose between "My Mac" and iOS devices even though the only platform listed in the Package file is macOS:
```
platforms: [
       .macOS(.v10_14)
    ],
```
Thanks

**Comment by tanner0101** [comment] 2020-02-17 22:32
Hmm that's strange. Xcode also lets me build on iOS simulator even though the platform isn't supported in the Package.swift file. That seems like an Xcode bug. I feel like I have seen the error work when trying to build an on older, unsupported version of macOS. 

FWIW, the reason we don't support iOS is because of how OpenSSL is currently linked. That may be fixed soon though since SwiftCrypto has been released.

**Comment by maxbritto** [comment] 2020-02-21 07:12
Is there really need of a vapor server running on an iOS device ?

**Comment by 0xTim** [comment] 2020-02-21 07:35
There is a small set of use cases where it _may_ be useful. E.g. running on device proxies to decrypt DRM content and provide it in the clear on a local webserver. Or running a test server locally etc for UI tests. I do agree that it's a fairly niche use case, but if it's almost free to support then why not

**Comment by Joannis** [comment] 2020-02-21 07:59
@tanner0101 realistically there'll be more issues than OpenSSL. For proper iOS support you'd need to support Network.framework sockets through all libs.

**Comment by tanner0101** [comment] 2020-02-21 23:27
Yeah good point. I started looking into NIO's network framework support a while back: https://github.com/vapor/vapor/pull/2123. That would need to be added for all packages that want to support iOS though.

**Comment by tanner0101** [comment] 2020-04-02 16:56
Duplicate of #2088

**Closed by tanner0101** 2020-04-02 16:56 UTC
Labels: question
