### ISSUE TITLE
Maximum concurrent Vapor WebSocket connections

### ISSUE THREAD

**Issue by potskhveria** [vapor/vapor#1694] opened 2018-05-22 18:58 UTC
How many Socket connections can a Vapor WebSocket server handle?

Using Vapor with WebSocket , is there a maximum number of concurrent connections that one can maintain before you need to add another server?

We deploy app with 50000 active users, is it recommend use Vapor?

Thanks in advance!

 🚀 Thank you for this great Framework! It is real amazing project

**Comment by twof** [comment] 2018-05-22 20:07
Someone else can speak up, but I don't believe Vapor has any hard limit on websocket connections. That's not to say things won't slow down if you open a million connections, but I haven't heard any complaints yet.

**Comment by MrLotU** [comment] 2019-01-30 21:03
Hi @potskhveria.

Like @twof said, there is no hard limit on WS Connections. If you, however, start running out of memory or something along those lines, it might be wise to make your application horizontally scalable. So you can have multiple instances running and divide the traffic over those instances.

I hope this is enough of an answer.

Because of the age of this issue, I'll close it. If you still have a question, feel free to open a new one :)

**Closed by MrLotU** 2019-01-30 21:03 UTC
Labels: question

**Comment by matejukmar** [comment] 2022-09-01 05:17
I'm testing my Vapor based ws server and I tried to connect 1400 ws connections in one minute to the server and it seems something happens at 999 connections as after that server became un-responsive to http or ws requests (forever until restart). Any idea what that could be (DDOS prevention?) and how to remove the limit? (I was running this on 4cpu linux/ubuntu server behind nginx and theoretically server should handle > 4000 connections - 1024 per CPU). I ran the test 2 times and in both cases server stopped at 999 connections.

**Comment by matejukmar** [comment] 2022-09-05 08:56
From the Vapor log I can see these lines at the point of breaking:
```
...
Sep 05 07:52:40 runProduction[2343858]: [ INFO ] GET /ws [request-id: 67ED3BF2-CD76-48A6-9F79-C9A5CF70FFA4]
Sep 05 07:52:40 runProduction[2343858]: [ INFO ] GET /ws [request-id: 00000000-0000-4000-8000-000000000000]
Sep 05 07:52:44 runProduction[2343858]: [ ERROR ] persistence.addMessage error: MySQL error: Duplicate entry: Duplicate entry '00000000000040008000000000000000' for key 'lmsg_message.PRIMARY'
```

Assigned request-id for the last ws connection shows NULL UUID for some reason. After that I get and error when saving message to the database with NULL UUID key as well (which is also weird)

**Comment by matejukmar** [comment] 2022-09-05 10:31
I was digging a little bit deeper and found out that the problem is due to RLIMIT_NOFILE (the maximum number of open file descriptors for the process) which was set to 1024 by default on my Digitalocean dropet.
This code solved the problem (inserted at Vapor startup inside configure call):
```swift
public func configure(_ app: Application) throws {
#if !os(macOS)
    var rlimit = rlimit(rlim_cur: 0, rlim_max: 0)
    getrlimit(__rlimit_resource_t(7), &rlimit)
    rlimit.rlim_cur = 4096
    setrlimit(__rlimit_resource_t(7), &rlimit)
    print("current limit", rlimit.rlim_cur, rlimit.rlim_max)
#endif
...
```
