### ISSUE TITLE
Resource temporarily unavailable after 30 seconds

### ISSUE THREAD

**Issue by skreutzberger** [vapor/vapor#689] opened 2016-11-04 10:19 UTC
Another socket issue that occurs after 30 seconds. It happens on Ubuntu 16.04 with Swift 3.0.1 and Vapor 1.1.10 on an EC2 instance running behind an Elastic Load Balancer:

`Server error: dispatch(Transport.StreamError.receive("There was a problem while receiving data.", Socket failed with code 11 ("Resource temporarily unavailable") [readFailed] "Unknown error"))`

Is it important or can we silence that error, too?

**Comment by LoganWright** [comment] 2016-11-04 12:56
@skreutzberger I'll look into this one as well to see if we can narrow down the cause. My guess is that its the same thing.

**Comment by andreasley** [comment] 2016-11-06 10:29
Most likely related to https://github.com/vapor/engine/commit/fb228be80617d19fe8fe6cb01208fc34f7090e35

**Comment by tannernelson** [comment] 2016-11-07 20:53
Closing this now since that commit was tagged. @skreutzberger please re-open if you see it again.

**Comment by andreasley** [comment] 2016-11-07 21:46
@tannernelson I think this issue exists because of the 30 second read timeout introduced in engine 1.1.1 and is still there. The read timeout is a workaround against stalling the server. If nonblocking operation will be enabled, the timeouts become irrelevant and this error shouldn't pop up anymore.

**Comment by LoganWright** [comment] 2016-11-07 23:20
Yea, we'll wait until non-blocking is in or catch this one as well, going to leave it open in interim.

**Comment by DevAndArtist** [comment] 2016-11-27 13:16
I'm also getting this issue on my Digitalocean droplet. :/

**Comment by voronianski** [comment] 2016-12-08 18:06
I'm also getting this issue

**Comment by tannernelson** [comment] 2016-12-15 22:20
@voronianski which version of Vapor are you using?

**Comment by voronianski** [comment] 2016-12-15 23:48
@tannernelson 1.1

**Comment by tannernelson** [comment] 2016-12-16 21:44
Try with Vapor 1.3.1. Just released: https://github.com/vapor/vapor/releases/tag/1.3.1

**Comment by voronianski** [comment] 2016-12-17 01:17
@tannernelson this message doesn't appear anymore. But another one is still here:

```
GET /build/app.css
Response had no 'Content-Type' header.
```

**Comment by tannernelson** [comment] 2016-12-19 18:25
@voronianski that looks like a separate issue. If you continue to see it, could you open an issue for it?

Closing this one since it appears to be resolved.

**Closed by tannernelson** 2016-12-19 18:25 UTC

**Comment by dylanreich** [comment] 2017-01-10 21:47
I am still having this issue with Vapor 1.0.3. Intermittently get the message `Server error: dispatch(Transport.StreamError.receive("There was a problem while receiving data.", Socket failed with code 11 ("Resource temporarily unavailable") [readFailed])`

**Comment by dylanreich** [comment] 2017-01-10 21:55
@tannernelson I am still having this issue with the latest version, 1.3.8. `Server error: dispatch(Transport.StreamError.receive("There was a problem while receiving data.", Socket failed with code 11 ("Resource temporarily unavailable") [readFailed])`

**Comment by c1wren** [comment] 2017-01-13 01:16
Having this same issue

**Comment by dylanreich** [comment] 2017-01-18 18:50
Can this issue be re-opened @tannernelson ?

**Comment by tannernelson** [comment] 2017-01-20 03:13
@dylanreich, @c1wren  could you specify what exactly you're trying to do when you encounter the error?

**Comment by georgealegre** [comment] 2017-02-06 04:56
@tannernelson I'm having the same issue. Installed a Hello World example on a EC2 instance behind a Load Balancer with Swift 3.0.2 and the latest version of Vapor. My guess is it's because of AWS health checks. The errors I'm seeing are always 30 seconds apart which is the interval for health checks on the Load Balancer I've set up. In fact, it's not even an issue, just something that caught my attention. Not like my app isn't running.

**Comment by oursnoir** [comment] 2017-03-01 17:18
Hi,
Same here ... (almost, I have an acceptFailed instead of readFailed)
`Server error: accept(Socket failed with code 11 ("Resource temporarily unavailable") [acceptFailed])`
But it doesn't seem to prevent the websocket server from functioning ...
my version is 1.5.7

**Comment by cikabole** [comment] 2017-03-04 23:03
v1.5.8 the same error shows 30 sec after each request. Running on (Digital Ocean) Ubuntu 16.04. 
Application is Hello World example from the documentation.
![screen shot 2017-03-05 at 00 03 07](https://cloud.githubusercontent.com/assets/688246/23582947/33fd1084-0137-11e7-86f4-4b05ae732807.png)

**Comment by skymaze** [comment] 2017-03-10 06:51
Same error follow doc getting-started guide -> hello-world
Swift version 3.0.2 (swift-3.0.2-RELEASE)
Vapor 1.5.9
Ubuntu 16.04

**Comment by rollr76518** [comment] 2017-03-12 04:20
Same issue with Google Cloud Service

Server error: dispatch(Transport.StreamError.receive("There was a problem while receiving data.", Socket failed with code 11 ("Resource temporarily unava
ilable") [readFailed]))

Vapor 1.1.0
Swfit version 3.0.1
Ubuntu 16.04

**Comment by AndrewSelvia** [comment] 2017-03-13 21:59
I'm seeing this error in my logs too:
`Server error: dispatch(Transport.StreamError.receive("There was a problem while receiving data.", Socket failed with code 11 ("Resource temporarily unavailable") [readFailed]`

I am making a POST request that could potentially last on the order of a few minutes. It may not be a good architecture, but it should work. I have a Spring/Java version of the same architecture that works, but the Swift version is stuck on this error for now.

Ubuntu 14.04.1 LTS
Vapor 1.5.8

**Comment by vlaminck** [comment] 2017-04-11 16:34
I'm seeing this on an EC2 instance behind a load balancer
    
    Server error: dispatch(Transport.StreamError.receive("There was a problem while receiving data.", Socket failed with code 11 ("Resource temporarily unavailable") [readFailed]))

Ubuntu 14.04
Swift 3.1
Vapor 1.5.15

**Comment by AndrewSelvia** [comment] 2017-04-12 23:45
@vlaminck The Vapor team made a change which solved this issue for me. I was seeing this issue for one of my endpoints that ran for a significant time period (i.e. more than 30s).

What helped me was this:
```
import HTTP
HTTP.defaultServerTimeout = 60 * 60
```

Just posting this in case it can help you.

**Comment by ACChe** [comment] 2017-04-18 06:04
Same error on DigitalOcean with Swift 3.1 and Vapor 1.5.15 under Ubuntu 16.04

**Comment by neurosaurus** [comment] 2017-05-18 00:13
@AndrewSelvia Where did you add that import and defaultServerTimeout statement?

I'm seeing the same issue under Ubuntu 16.04, Swift 3.1, and Vapor 1.5

**Comment by AndrewSelvia** [comment] 2017-05-18 00:15
@neurosaurus I added it at global scope within my project's `main.swift`.

**Comment by neurosaurus** [comment] 2017-05-18 00:15
@AndrewSelvia And it solved the issue?

**Comment by AndrewSelvia** [comment] 2017-05-18 00:16
@neurosaurus Yes.

**Comment by neurosaurus** [comment] 2017-05-18 00:18
@AndrewSelvia Not for me, unfortunately. :(
