### ISSUE TITLE
Requests from vapor client corrupts SQLite database in vapor server

### ISSUE THREAD

**Issue by moppymopperson** [vapor/vapor#1707] opened 2018-06-02 12:53 UTC
I have a simple little Vapor server running. It's less code than the boilerplate that is generated for a new project, and all it does is query an empty table and return the results.

When I send a request to the server from curl or Postman, it behaves as expected, returning an empty array. I wrote a second simple Vapor server that is supposed to send a request to the first. However, when the request comes from the 2nd Vapor server, an error is thrown. 

`[ ERROR ] SQLiteError.error: no such table: nodes (SQLiteQuery.swift:91)`

After that, all requests from any origin result in the same error.

### Steps to reproduce

I've created a minimum replicable example by shaving away unrelated code from my project. Clone the repository [here](https://github.com/moppymopperson/mopchain/tree/reproduce-bug-minimal) and make sure you have the correct branch checked out.

Open both `mopchain-hub` in XCode and run it. Watching the console output, send a curl request. `curl http://localhost:3000/nodes`. You'll get back an empty array. 

Next run mopchain `mopchain-node`. During the boot sequence it sends a request to the same endpoint you just tested with curl. This time, instead of returning an empty array, the `mopchain-hub` will throw an exception. `[ ERROR ] SQLiteError.error: no such table: nodes (SQLiteQuery.swift:91)`

If you try sending another request from curl, it will now result in an error as well. 

The full repository is provided above. All irrelevant code has been removed.

The only difference between the happy case and the sad case is the `req` parameter.

Server code (configure)

    // Configure a SQLite database
    let sqlite = try SQLiteDatabase(storage: .memory)
    
    // Register the configured SQLite database to the database config.
    var databases = DatabasesConfig()
    databases.add(database: sqlite, as: .sqlite)
    services.register(databases)
    
    // Configure migrations
    var migrations = MigrationConfig()
    migrations.add(model: Peer.self, database: .sqlite)
    services.register(migrations)

    // Setup `PeerService`
    let peerService = PeerService()
    services.register(peerService)

Server code (controller)

    /** Fetch all `Nodes` */
    func index(_ req: Request) throws -> Future<[Node]> {
        let logger = try req.make(Logger.self)
        logger.info("Received request to for all Node records")
        return Node.query(on: req).all()
    }

Client code
    
    /** Anychronously fetch all the peers from the hub server */
    func fetchNetworkPeersFromHub(in container: Container) throws -> Future<[Peer]> {
        return try container.client().send(.GET, to: "http://localhost:3000/nodes").flatMap({ response in
            return try response.content.decode([Peer].self)
        })
    }

From Vapor client (doesn't work)
```
GET /nodes HTTP/1.1
cache-control: no-cache
Postman-Token: 2fcc907e-a334-4edd-b445-a05a29e5a15f
User-Agent: PostmanRuntime/7.1.1
Accept: */*
Host: localhost:3000
accept-encoding: gzip, deflate
Connection: keep-alive
<no body>
```

From Postman (works)
```
GET /nodes HTTP/1.1
Host: localhost:3000
Connection: keep-alive
Accept: */*
User-Agent: Run (unknown version) CFNetwork/902 Darwin/17.7.0 (x86_64)
Accept-Language: en-us
Content-Length: 0
Accept-Encoding: gzip, deflate
<no body>
```

Turning on debugging confirms that the table is created and that both requests result in the same SQLite query being generated.
```
[ INFO ] Migrating 'sqlite' database (FluentProvider.swift:28)
[sqlite] [2018-06-02 06:42:25 +0000] SELECT count(*) as `fluentAggregate` FROM `fluent` []
[sqlite] [2018-06-02 06:42:25 +0000] CREATE TABLE `fluent` (`id` BLOB PRIMARY KEY, `name` TEXT NOT NULL, `batch` INTEGER NOT NULL, `createdAt` REAL, `updatedAt` REAL) []
[sqlite] [2018-06-02 06:42:25 +0000] SELECT * FROM `fluent` ORDER BY `fluent`.`batch` DESC LIMIT 1 OFFSET 0 []
[sqlite] [2018-06-02 06:42:25 +0000] SELECT * FROM `fluent` WHERE (`fluent`.`name` = ?) LIMIT 1 OFFSET 0 ["Node"]
[ INFO ] Preparing migration 'Node' (MigrationContainer.swift:50)
[sqlite] [2018-06-02 06:42:25 +0000] CREATE TABLE `nodes` (`id` INTEGER PRIMARY KEY, `address` TEXT NOT NULL) []
[sqlite] [2018-06-02 06:42:25 +0000] INSERT INTO `fluent` (`batch`, `id`, `createdAt`, `updatedAt`, `name`) VALUES (?, ?, ?, ?, ?) ["1", "54664644-4565-44DB-9163-1BF1538B9DD4", "1527921745.50961", "1527921745.50961", "Node"]
[ INFO ] Migrations complete (FluentProvider.swift:32)

Server starting on http://localhost:3000

// Request from curl
[ INFO ] Received request to for all Node records (NodeController.swift:9)
[sqlite] [2018-06-02 06:42:50 +0000] SELECT * FROM `nodes` []

// Request from Vapor
[ INFO ] Received request to for all Node records (NodeController.swift:9)
[sqlite] [2018-06-02 06:43:04 +0000] SELECT * FROM `nodes` []
[ ERROR ] SQLiteError.error: no such table: nodes (SQLiteQuery.swift:91)
```

### Expected behavior

The response should be an empty array in both cases, with no exception thrown.

### Actual behavior

When the origin of the request is the 2nd Vapor server, querying the database corrupts the data.

### Environment

* Vapor Framework version: 3
* Vapor Toolbox version: Vapor Toolbox: 3.1.7
* OS version: macOS 10.13.6 Beta (17G31f)

**Comment by fredpi** [comment] 2018-07-04 09:01
I have a similar configuration and am experiencing this exact same issue. Any ideas to solve this?

**Comment by moppymopperson** [comment] 2018-07-04 09:18
Unfortunately I never found a solution.

**Comment by 0xTim** [comment] 2018-07-06 10:12
Is this reproducible if using MySQL/Postgres?

**Comment by moppymopperson** [comment] 2018-07-07 00:38
MySQL and Postgres are both untested.

**Comment by vzsg** [comment] 2018-07-07 19:11
I've been playing around with the repro project, because this issue is so curiously horrifying and absurd, with no actual result.

But I've noticed that if I call the `GET /nodes` route eight times (== number of cores), 9 SQLite connections are opened in total, and this "no such table" error no longer appears.

**Comment by tanner0101** [comment] 2018-09-19 15:39
According to [SQLite's threading docs](https://www.sqlite.org/threadsafe.html):

> The SQLITE_OPEN_NOMUTEX flag causes the database connection to be in the multi-thread mode and the SQLITE_OPEN_FULLMUTEX flag causes the connection to be in serialized mode.

We use the `SQLITE_OPEN_FULLMUTEX ` when initializing a [`SQLiteDatabase`](https://github.com/vapor/sqlite/blob/master/Sources/SQLite/Database/SQLiteDatabase.swift#L39). This is in order to make the special `:memory:` storage type work correctly. By using the serialized threading mode, we should theoretically be able to share a single database handle (connection) over multiple threads. (Being able to share a single database handle is important because `:memory:` is local to a given handle.)

Might be worth testing if adding some locks to the [`query`](https://github.com/vapor/sqlite/blob/master/Sources/SQLite/Database/SQLiteConnection.swift#L78) method would fix this?

We could also revert back to a hack we were using in one of the betas where SQLite's "memory" storage type was actually just using a file in `/tmp/`. (The file would be deleted each time the app booted).

**Comment by tanner0101** [comment] 2018-09-19 15:42
FWIW, this bug should probably be filed in https://github.com/vapor/sqlite/issues unless we have reason to believe it's a problem w/ Vapor's source code specifically.

**Comment by MrLotU** [comment] 2019-11-17 15:32
With Vapor 4 in Beta and no discussion for over a few months, I'm closing this issue. Feel free to re-open if there are still questions/issues unanswered.

**Closed by MrLotU** 2019-11-17 15:32 UTC
Labels: bug

**Comment by bblacey** [comment] 2019-12-19 19:43
This still seems to be an issue with 4.0.0-beta.2 under Xcode 11.3.

Package Configuration
```
// swift-tools-version:5.1
import PackageDescription

let package = Package(
    name: "app",
    platforms: [
       .macOS(.v10_14)
    ],
    products: [
        .executable(name: "Run", targets: ["Run"]),
        .library(name: "App", targets: ["App"]),
    ],
    dependencies: [
        // 💧 A server-side Swift web framework.
        .package(url: "https://github.com/vapor/vapor.git", from: "4.0.0-beta.2"),
        .package(url: "https://github.com/vapor/fluent.git", from: "4.0.0-beta.2"),
        .package(url: "https://github.com/vapor/fluent-sqlite-driver.git", from: "4.0.0-beta.2"),
    ],
    targets: [
        .target(name: "App", dependencies: ["Fluent", "FluentSQLiteDriver", "Vapor"]),
        .target(name: "Run", dependencies: ["App"]),
        .testTarget(name: "AppTests", dependencies: ["App", "XCTVapor"])
    ]
)
```

Database initialization

```
Test Case '-[AppTests.AppTests testCreateTodo]' started.
2019-12-19T13:13:46-0500 info: read fluent fields=[fluent.id, fluent.name, fluent.batch, fluent.created_at, fluent.updated_at]
2019-12-19T13:13:46-0500 info: read fluent fields=[fluent.id, fluent.name, fluent.batch, fluent.created_at, fluent.updated_at]
2019-12-19T13:13:46-0500 info: read fluent fields=[fluent.id, fluent.name, fluent.batch, fluent.created_at, fluent.updated_at]
2019-12-19T13:13:46-0500 info: create fluent fields=[name, updated_at, batch, created_at, id] input=[["CreateTodo", Optional(2019-12-19 18:13:46 +0000), 1, Optional(2019-12-19 18:13:46 +0000), default]]
2019-12-19T13:13:46-0500 info: request-id=42803193-F584-4628-8BFF-EF04DF43616B GET /todos
2019-12-19T13:13:46-0500 info: request-id=42803193-F584-4628-8BFF-EF04DF43616B read todos fields=[todos.id, todos.title]
2019-12-19T13:13:46-0500 info: request-id=3D8DFA22-74A2-4F91-B37A-5E8EF8A3CD8C POST /todos
2019-12-19T13:13:46-0500 info: request-id=3D8DFA22-74A2-4F91-B37A-5E8EF8A3CD8C create todos fields=[id, title] input=[[default, "Test My App"]]
2019-12-19T13:13:46-0500 info: request-id=81AAED44-B9A6-4652-A432-1EA86E18FDE8 GET /todos
2019-12-19T13:13:46-0500 info: request-id=81AAED44-B9A6-4652-A432-1EA86E18FDE8 read todos fields=[todos.id, todos.title]
Test Case '-[AppTests.AppTests testCreateTodo]' passed (0.145 seconds).
```

Attempt to create a todo

```
[ NOTICE ] Server starting on http://127.0.0.1:8080
[ INFO ] POST /todos
[ INFO ] create todos fields=[title, id] input=[["some random todo", default]]
[ ERROR ] error: no such table: todos
```

**Comment by torianin** [comment] 2020-04-06 09:57
@bblacey The ```Use custom working directory``` setting in Xcode solved ```no such table``` issue for me.

**Comment by keyle** [comment] 2023-03-18 13:23
for the record, because it was hard to find for me, the details on how to solve it is here

https://github.com/vapor/vapor/issues/2131#issuecomment-622264085

**Comment by dmoroz0v** [comment] 2023-11-05 05:19
I call ```app.autoMigrate()```
```
app.databases.use(DatabaseConfigurationFactory.sqlite(.file("db.sqlite")), as: .sqlite)
app.migrations.add(CreateFlowStorage())
app.autoMigrate()
```
