### ISSUE TITLE
Can't send emoji in plain text

### ISSUE THREAD

**Issue by NathanFlurry** [vapor/vapor#516] opened 2016-08-06 10:13 UTC
# Bugs

When sending emojis in a plain text response, they show up incorrectly. For example, this code:

```swift
let drop = Droplet(providers: [VaporMustache.Provider.self])
drop.get("/") { request in
	return "🙄"
}
let port = drop.config["app", "port"].int ?? 80
drop.serve()
```

gives me `ðŸ™„` when I visit the homepage.

However, when I do the same thing using JSON, it appears just fine.

**Comment by tannernelson** [comment] 2016-08-06 15:17
Good find. Must be some issue with `String`'s conformance to `ResponseRepresentable.

**Comment by LoganWright** [comment] 2016-08-22 19:32
My guess is that the issue is something to do with encoding, what happens if you do:

```swift
return Response(headers: ["Content-Type": "text/plain; charset=utf-8"], body: .data("🙄".bytes))
```

If that fixes it we know that we need to add the charset.

**Comment by tannernelson** [comment] 2016-08-25 23:21
@NathanFlurry I assume this worked? Closing for now.

**Closed by tannernelson** 2016-08-25 23:21 UTC
Labels: bug

**Comment by NathanFlurry** [comment] 2016-08-26 05:57
@tannernelson Yeah, @LoganWright's solution worked. However, is there any reason why the charset is not set automatically [here](https://github.com/vapor/engine/blob/master/Sources/HTTP/Models/Response/ResponseRepresentable.swift#L24)?

**Comment by tannernelson** [comment] 2016-08-26 06:23
https://github.com/vapor/engine/issues/42
