### ISSUE TITLE
Multipart Errors are reported as internal server errors

### ISSUE THREAD

**Issue by 0xTim** [vapor/vapor#2650] opened 2021-07-12 16:43 UTC
When sending a request body that decodes a `Content` type. If the request is sent as multipart with the right header set, but the body is empty, a 500 error is returned. This can cause problems with apps that have automatic reporting for internal server errors as it should be reported as a bad request

**Comment by JakeTiritilli** [comment] 2021-08-07 18:08
I’ll work on trying to fix this one.

**Comment by jareyesda** [comment] 2022-05-08 18:49
@0xTim @BennyDeBock, Is this still an issue? Was looking into it but it seems like it was resolved.

The private `_ContentContainer` struct for a `Request` object has its `decode` method throw `Abort(.unprocessableEntity)` when `body` is `nil`. Line 76 inside `Request.swift`.

Here's a snipper of the `decode` method:

```
func decode<D>(_ decodable: D.Type, using decoder: ContentDecoder) throws -> D where D : Decodable {
   guard let body = self.request.body.data else {
       self.request.logger.debug("Request body is empty. If you're trying to stream the body, decoding streaming bodies not supported")
       throw Abort(.unprocessableEntity)
   }
   return try decoder.decode(D.self, from: body, headers: self.request.headers)
}
```

**Comment by paunik** [comment] 2022-05-23 13:00
@jareyesda  I have opened MR that covers that some while ago, now i have rebased and ran the tests, seems that issue is still present. If You can check, do I need to add some more things or we should close this MR.
Best

**Comment by MahdiBM** [comment] 2022-07-09 14:40
I came across this issue when i was looking at [one of the boards](https://github.com/orgs/vapor/projects/10).
I could not reproduce this issue. What the issue expects is if you run this [existing test](https://github.com/vapor/vapor/blob/cd91a66c7dd2d8658c9fc43ee9d96d7a259bbc5c/Tests/VaporTests/ContentTests.swift#L147), but with empty body (set to `nil` or `.init()`), it should throw a 5xx error. That's not the case and it will instead throw a un-processable entity error. Non-empty bad bodies also just throw a bad request error.

**Comment by BennyDeBock** [comment] 2022-07-11 14:09
@jareyesda as far as i'm aware, this hasn't been solved yet if it's still on the board. 

@MahdiBM maybe you could ask @0xTim for more details as to how to reproduce the issue.

**Comment by MahdiBM** [comment] 2022-07-11 14:18
@BennyDeBock I'll be happy to have a reproducible example on my hands but to me seems that what @jareyesda is correct. There is an explicit line in the decoder to throw a un-processable entity error in case the body is empty.
@paunik says the issue is not resolved so i'm curious to know how he has tested the problem.

**Comment by 0xTim** [comment] 2022-07-25 10:13
Here's a test from @paunik that should fail if it's still not fixed 

https://github.com/paunik/vapor/commit/6e0fc090ed6c8cce2b0bc830d41d09acc4b0ded1

**Comment by jareyesda** [comment] 2022-07-29 21:45
> 

Confirmed, @paunik 's test `testMultipartDecodedEmptyMultipartForm()` is failing with an empty body. Looking further into the issue

**Comment by jareyesda** [comment] 2022-07-29 21:55
My apologies if I'm being spammy - but @paunik 's [PR](https://github.com/vapor/vapor/pull/2674) seems like it will solve the issue 👍🏻🥳

Thank you!

**Closed** 2023-08-16 04:26 UTC
Labels: good first issue
