### ISSUE TITLE
EngineClient fails to resolve localhost

### ISSUE THREAD

**Issue by vzsg** [vapor/vapor#1086] opened 2017-07-14 22:42 UTC
* Vapor Version: 2.1.2
* OS: macOS
* OS Version: 10.12.5 (16F73)
* Vapor Toolbox Version: ¯\_(ツ)_/¯

### Expected Behavior

Sending HTTP requests to another service on localhost should Just Work with both the Engine and the Foundation HTTP client.

### Current Behavior

When using the Engine client (which is also the default), the following error is thrown from [TCPInternetSocket.swift line66](https://github.com/vapor/sockets/blob/2.0.1/Sources/Sockets/TCP/TCPInternetSocket.swift#L66):

```
[Sockets Error: Failed trying to connect to http://localhost:8000] [Identifier: Sockets.SocketsError.connectFailed] [Possible Causes: The hostname or port is not valid]
```

The `errno` is `61`.

### How to Reproduce

1. Create a Swift project that depends on Vapor.
1. In the project root, run `python -m SimpleHTTPServer &` to get a file server up and running.
1. Add the following line to your Swift project:
    ```swift
    try EngineClient.factory.get("http://localhost:8000/Package.swift")
    ```
1. Observe the error.
1. Replace the client with FoundationClient:
    ```swift
    try FoundationClientFactory().get("http://localhost:8000/Package.swift")
    ```
1. Observe that the call runs perfectly.

**Comment by ckd** [comment] 2017-07-17 16:13
So, fair warning... I haven't thought about any of this in over ten years, and it's not a certainty that I understood it back then either.

That said, this is due, I believe, to differences in the various flags that are passed to getaddrinfo in Swift's foundation libs versus Vapor's Engine Client. The way I THINK it works in the Foundation implementation is that it attempts to resolve things via DNS, and failing that, tries other methods (which is where localhost would actually get resolved correctly).

If it's intentional, Engine is operating in a stricter and arguably more performant manner... you can actually see this yourself by doing an "nslookup localhost" from a macOS terminal- this should fail because nslookup ONLY relies on DNS. Lots of Linux systems now implement some fancy DNS magic to make local and server lookups seamless, but macOS does not.

So, the inability to resolve "localhost" isn't necessarily a bug, but could be a performance optimization. You'd have to ask @tanner0101 about his intention in that regard.

The simple workaround is to use the loopback address instead of using the hostname or just use FoundationClient.

**Comment by vzsg** [comment] 2017-07-17 20:23
If it really is a performance optimization, it's definitely a premature one.

**Comment by tanner0101** [comment] 2017-07-19 20:41
@ckd the socket package was originally written by @czechboy0. He'd be able to answer the question regarding whether or not this was a performance concern. My guess is that being able to resolve localhost is an extra step that was simply not implemented.

That being said, I'm wondering if simply replacing `"localhost"` with `"127.0.0.1"` would work as a solution?

**Comment by TG908** [comment] 2017-07-26 23:53
So it seem like the python simpleHttpServer doesnt support IPv6 in this configuration wich is causing the SocketError.connectFailed

**Comment by tanner0101** [comment] 2017-08-07 19:37
@TG908 have you confirmed the changes mentioned fix your issue? We could release this as a minor release if we add a computed `public let address: ResolvedInternetAddress` that returns the first address in the array.

**Comment by tanner0101** [comment] 2017-08-07 20:05
@TG908 @ckd can you verify if the fix in https://github.com/vapor/sockets/pull/137 works or add in a failing test case if you have one.

**Comment by tanner0101** [comment] 2017-08-08 00:06
Closing here, track https://github.com/vapor/sockets/pull/137

**Closed by tanner0101** 2017-08-08 00:06 UTC
Labels: bug
