### ISSUE TITLE
Removing routes at runtime

### ISSUE THREAD

**Issue by ViktorEarth** [vapor/vapor#1797] opened 2018-09-01 16:16 UTC
There is the need to remove registered routes at runtime and create new ones at runtime.
On the one hand, it should be possible to delete all registered routes to create new ones at runtime, on the other hand, it should be possible to delete a single route based on the path.

1) router.dropRoutes()
2) router.dropRoute(with path: String)

I tried to implement it, but i failed so far.
I am willing to pay/donate for an Expert of the Vapor Team, for adding these 2 features in a view days.

### Environment

* OS version: macOS 10.13.6

**Comment by mzinner** [comment] 2018-09-04 08:27
This feature would be really helpful to implement a true dynamic solution. I would certainly use this feature in my current project. Please consider adding this functionality.

**Comment by LoganWright** [comment] 2018-09-17 11:13
Hi @ViktorEarth, 

Unfortunately adding this to the router isn't exactly possible. The issue is that if we were to mutate the router object directly on one server, this wouldn't apply to all servers on the network, but rather a single instance. When the user connects to another node in the network, the route won't exist.

Instead, it would be better to setup some sort of middleware that connects to a database representation of active routes that would be shared across your whole network and have this decide how and if a request should be processed.

You might also group them into a special handler:

```swift
let hotswaps = router.grouped(HotSwapMiddleware())
hotswaps.get(.catchall) { req in 
    /// all routes approved by your middleware will come here and be handled manually
}
```

Hope this helps get you pointed in the right direction! I'm closing this for now since it's not something we can add to the vapor library, but happy to comment on this thread if you get stuck, or even better, join us in Discord while you work it out!

**Closed by LoganWright** 2018-09-17 11:13 UTC
