### ISSUE TITLE
Support Vapor running inside of an iOS app

### ISSUE THREAD

**Issue by adamstener** [vapor/vapor#2270] opened 2020-03-27 16:56 UTC
I'd like to be able to spin up a local web server inside of an iOS app for integration testing, stubbing, or presentation content modifications.

The vast majority of apps rely on some kind of data from a server.  Many times an app is in development and the server component is not yet ready for consumption.  It would be nice to be able to fully test out an app against a local server that is responding with data in much the same way that a deployed server would, without having to build and deploy your own external application.

Other use cases could be to quickly modify the content being served, on device, for demo or testing purposes.  There could also be benefits for having this server spin up during CI to have more control over integration tests "hitting the wire".

### Expected behavior

I can start a Vapor app from within the iOS app that runs at the same time as the application itself.

### Actual behavior

-

### Environment

* Vapor Framework version:
* Vapor Toolbox version:
* OS version:

**Comment by tanner0101** [comment] 2020-04-02 17:33
Duplicate of #2088

**Closed by tanner0101** 2020-04-02 17:33 UTC
Labels: enhancement
