### ISSUE TITLE
Unable to decode a UUID from Vapor.Content

### ISSUE THREAD

**Issue by michael-mckenna** [vapor/vapor#2621] opened 2021-05-07 20:57 UTC
Hey all,

I am sending a UUID in the request body for a POST endpoint, and the decoder seems to be unable to decode the UUID. The function is:

```
    func create(req: Request) throws -> EventLoopFuture<Model.Response> {
        let request = try req.content.decode(Model.Request.self)
        print(req.body.string) // prints ("id=<uuid>&name=randomtext&otherId=<uuid>")
        ...
```

The `otherId` is indeed present in the body.  The `Model.Request` struct is as follows:

```
struct Model {
    struct Request: Content {
        let id: UUID?
        let name: String
        let otherId: UUID?
    }
}
```

However, `request.otherId` is null. I expected it to be the UUID sent in the request.

I am using Vapor 4.39.1, Xcode 12.4.

**Comment by 0xTim** [comment] 2021-05-07 22:07
Can you show the actual request body and not the replaced bits?

**Comment by michael-mckenna** [comment] 2021-05-10 14:19
@0xTim Here's what I'm sending from Postman:

```
{
    "name": "Random String",
    "id": "{{$randomUUID}}",
    "otherId": "013BBBCD-A40C-4A93-8236-2C184D190VBA"
}
```

Oh and to be clear - both `id` and `otherId` are null after decoding, and they are of type `UUID`.

**Comment by 0xTim** [comment] 2021-05-11 13:47
@michael-mckenna `"013BBBCD-A40C-4A93-8236-2C184D190VBA"` is not a valid idea - it should be hex based. I've tried

```swift
    app.post("uuid") { req -> String in
        let data = try req.content.decode(SomeData.self)
        return data.otherId?.uuidString ?? "Not Found"
    }

struct SomeData: Content {
    let id: UUID?
    let name: String
    let otherId: UUID?
}
```

With the request `curl -X POST http://localhost:8080/uuid -H "content-type: application/json" -d "{ \"name\": \"Some name\", \"id\": \"013BBBCE-A40C-4A93-8236-2C184D190DBA\", \"otherId\": \"013BBBCD-A40C-4A93-8236-2C184D190EBA\"}"` and it works fine for me. I suggest checking the UUIDs generated are valid v4 UUIDs

**Comment by 0xTim** [comment] 2021-05-24 15:04
I'll close this as I can't reproduce but feel free to reopen if it's still an issue!

**Closed by 0xTim** 2021-05-24 15:04 UTC
