### ISSUE TITLE
Slow compilation

### ISSUE THREAD

**Issue by wildfiremedia** [vapor/vapor#611] opened 2016-09-17 17:33 UTC
Modified code in main.swift and recompile took sometime which is unacceptable
Need to skip those folders that are already compiled and straight to compile main.swift
```
Compile Swift Module 'TurnstileCrypto' (3 sources)
Compile Swift Module 'Jay' (21 sources)
Compile Swift Module 'Fluent' (35 sources)
Compile Swift Module 'Core' (28 sources)
Compile Swift Module 'Turnstile' (13 sources)
Compile Swift Module 'Leaf' (33 sources)
Compile Swift Module 'Console' (34 sources)
Compile Swift Module 'TLS' (7 sources)
Compile Swift Module 'Essentials' (2 sources)
Compile Swift Module 'TurnstileWeb' (8 sources)
Compile Swift Module 'Random' (3 sources)
Compile Swift Module 'Cipher' (2 sources)
Compile Swift Module 'JSON' (7 sources)
Compile Swift Module 'HMAC' (2 sources)
Compile Swift Module 'Hash' (3 sources)
Compile Swift Module 'BCrypt' (1 sources)
Compile Swift Module 'URI' (9 sources)
Compile Swift Module 'Transport' (8 sources)
Compile Swift Module 'SMTP' (21 sources)
Compile Swift Module 'HTTP' (33 sources)
Compile Swift Module 'WebSockets' (14 sources)
Compile Swift Module 'Settings' (10 sources)
Compile Swift Module 'Routing' (9 sources)
Compile Swift Module 'Cookies' (11 sources)
Compile Swift Module 'Cache' (3 sources)
Compile Swift Module 'Sessions' (6 sources)
Compile Swift Module 'Auth' (14 sources)
Compile Swift Module 'HTTPRouting' (5 sources)
Compile Swift Module 'TypeSafeRouting' (3 sources)
Compile Swift Module 'Vapor' (83 sources)
Compile Swift Module 'App' (3 sources)
```

**Comment by NathanFlurry** [comment] 2016-09-17 20:49
That is one of the biggest complaints about Swift — the compilation times.

For now, try out `vapor xcode` and build from Xcode (assuming you have a Mac). This will dramatically speed up compilation times after the first build. Theoretically, building like `swift build -Xswiftc -O` would prevent recompilation of all the libraries every time you build, but it doesn't seem to work.

[This](https://thatthinginswift.com/debug-long-compile-times-swift/) may be a good thing to look into to speed up compilation times.

**Comment by tannernelson** [comment] 2016-09-19 15:46
@LoganWright were the SPM guys talking about a way that adding a modulemap could make this faster?

**Comment by Linicks** [comment] 2016-09-19 18:13
I'm also seeing long compile times, on MacOS, and Ubuntu 16.04 with swift 3.0 release.  I realize that this is primarily a compiler issue, but thought I would report this behavior as well.  These long compile times make it very difficult to be productive.  I hope they get this sorted out soon!

**Comment by tannernelson** [comment] 2016-09-19 22:31
We're working with the Swift Package Manager team to find a solution. For now, use Xcode for fast build times. The next patch or minor version to Swift will likely fix this.

**Comment by MoridinBG** [comment] 2016-10-04 11:41
Xcode 8 can sometimes recompile the entire project for seemingly no purpose. The issue is with the compiler and it affects both swift 2.3 and 3.0
You can use the following defaults entry to debug compilation issues:
    defaults write com.apple.dt.Xcode ExplainWhyBuildCommandsAreRun -bool true
The output is buried in the build output, but in Xcode can be found under "Build target XXX" -> "Compile Swift source files"
The bug (which is known and my rdar had been marked as duplicate) boils down to
    "(running because command line arguments are different from the last time)"

**Comment by LoganWright** [comment] 2016-10-28 17:21
We made some underlying tweaks to improve compilation on our end. Also w/ Xcode 8.1 released, the underlying Swift Compiler is resolved.

**Closed by LoganWright** 2016-10-28 17:21 UTC

**Comment by TrueMax** [comment] 2017-01-29 12:27
A compilation of a simple Vapor project in XCode 8.2.1 hangs it dead. It is totally unacceptable.

**Comment by buglinjo** [comment] 2017-05-03 21:27
I'm running Vapor on my Ubuntu 16.04 server. `swift build -c release` takes about 10 minutes to build :D How can I improve this?

**Comment by wildfiremedia** [comment] 2017-05-04 00:01
Do you lot of dictionary in Swift? This is one of the issue that Swift took
long time to compile.

**Comment by wildfiremedia** [comment] 2017-05-04 00:06
Please sought help with Vapor community in Slack channel, this is closed and unrelated to future bugs.
