### ISSUE TITLE
Bcrypt.verify() throws compiler error

### ISSUE THREAD

**Issue by simonedelmann** [vapor/vapor#2265] opened 2020-03-25 18:08 UTC
When running `Bcrypt.verify()` via `swift run Run` this always throws a compiler error.

### Steps to reproduce

Add ~~one of these~~ lines to `main.swift`:

```swift
// Test BCrypt
let correctHash = try! Bcrypt.verify("password", created: "$2b$12$Ju7bigpFfjGCiIbqgx7W/uvieIMgj4.ppGLlsFN8j5KW2kOGavljS")
```

### Expected behavior

~~This should result either `true` or `false`.~~
This should result `true`.

### Actual behavior

When running via command-line (via `swift run Run`), this throws an compiler error:

Correct hash:
```
[1]    15147 segmentation fault  swift run Run
```

~~Wrong hash~~

### Environment

I've used a fresh Vapor 4 template (March 25th 18:00 UTC), Xcode 11.4 Release, Swift 5.2 Release

**Comment by simonedelmann** [comment] 2020-03-25 18:10
Here is a zip file:
[vaporBug.zip](https://github.com/vapor/vapor/files/4382673/vaporBug.zip)

**Comment by 0xTim** [comment] 2020-03-26 13:59
@simonedelmann that's expected behaviour because `WRONG` isn't a valid hash so it's throwing an error. If the has wash valid, but was a hash for say `password1234` then you'd get `false`.

**Comment by simonedelmann** [comment] 2020-03-26 16:51
@0xTim I see! Still the `segmentation fault` seems to be a bug. I will edit the issue above.

**Comment by tanner0101** [comment] 2020-03-26 17:08
I'm able to re-create this but I have no idea what could be causing it. It seems to crash when calling `bcrypt_hashpass` which is part of the `CBcrypt` module. 

I've opened an SR here: https://bugs.swift.org/browse/SR-12424

**Comment by tanner0101** [comment] 2020-04-02 17:26
Closing this here since there's an SR-12424 tracking the issue.

**Closed by tanner0101** 2020-04-02 17:26 UTC
Labels: bug

**Comment by vojtarylko** [comment] 2021-06-24 07:37
If somebody stumbles across this: The original issue SR-12424 regressed, follow https://bugs.swift.org/browse/SR-14543
