### ISSUE TITLE
Support manually upgrading Request to WebSocket

### ISSUE THREAD

**Issue by lmcd** [vapor/vapor#2196] opened 2020-02-24 20:49 UTC
I'd like to upgrade to a WebSocket manually, so I have an opportunity to reject the request/`throw` beforehand, just like other sorts of requests.

This should be possible, but `upgrader` is `internal`:

```swift
app.on(.GET, "ws") { req -> Response in
    // Check request here and throw if needed
    
    let res = Response(status: .switchingProtocols)
    res.upgrader = .webSocket(onUpgrade: { ws in
        // Handle WebSocket lifecycle here
    })
    
    return res
}
```

**Comment by lmcd** [comment] 2020-02-24 21:35
Added PR here: https://github.com/vapor/vapor/pull/2197

**Comment by tanner0101** [comment] 2020-04-02 16:58
As mentioned in the referenced PR, this API was proposed:
```swift
app.get("socket") { req in 
    // Check things from request.
    return req.webSocket { ws in
        // Use upgraded WebSocket.
    }
}
```

**Comment by robnadin** [comment] 2020-05-13 08:40
How will this look when you need to modify the response as part of the opening handshake?

In my case, I'm writing an MQTT handler and the specification requires that the server includes a `Sec-WebSocket-Protocol` header field with the agreed subprotocol requested by the client:
```
app.on(.GET, "mqtt") { req -> Response in
    let supportedProtocols = ["mqtt", "mqttv3.1"]
    let availableProtocols = req.headers[.secWebSocketProtocol].filter(supportedProtocols.contains)
    
    guard let agreedProtocol = availableProtocols.first else {
        throw Abort(.badRequest)
    }
        
    let res = Response(status: .switchingProtocols)
    res.headers.replaceOrAdd(name: "Sec-WebSocket-Protocol", value: agreedProtocol)
    res.upgrader = Response.Upgrader.webSocket(maxFrameSize: WebSocketMaxFrameSize.default, onUpgrade: { ws in
        // Use upgraded WebSocket.
    })
    
    return res
}
```

Would the `req.webSocket(onUpgrade:)` closure be chainable in this instance?

**Comment by tanner0101** [comment] 2020-05-27 15:50
Looks like this is a dupe of https://github.com/vapor/vapor/issues/2235. We should definitely allow for custom response headers to be added. @robnadin would you mind making a note on that issue to add a test and example code for sending the `"Sec-WebSocket-Protocol"` header?

**Closed by tanner0101** 2020-05-27 15:50 UTC
Labels: enhancement
