### ISSUE TITLE
Can't use latest version of Vapor on mac with Xcode 9.4.1

### ISSUE THREAD

**Issue by sergiocampama** [vapor/vapor#1768] opened 2018-07-22 13:41 UTC
Adding the Vapor dependency on my Package.swift with version 3.0.6 makes `swift run Target` hang forever.

### Steps to reproduce

```
// swift-tools-version:4.1

import PackageDescription

let package = Package(
    name: "MyProject",
    products: [
        .executable(
            name: "MyExecutable",
            targets: ["MyExecutable"])
    ],
    dependencies: [
        .package(url: "https://github.com/vapor/vapor.git", from: "3.0.6"),
    ],
    targets: [
        .target(
            name: "MyExecutable",
            dependencies: ["Vapor"])
    ]
)
```

`swift build MyExecutable`

### Expected behavior

That the project would build.

### Actual behavior

Hangs forever on fetching dependencies.

### Environment

* Vapor Framework version: 3.0.6
* Vapor Toolbox version: Not installed.
* OS version: 10.14b4 / Xcode 9.4.1

**Comment by vzsg** [comment] 2018-07-22 17:41
It's surely valid (not everything needs to start with the api-template anyway). It also resolved fine for me, so I'm thinking that there's a local issue (like not running `swift package update` after changing the file).

**Comment by grundoon** [comment] 2018-07-22 17:57
Okay, I'll certainly retract that first sentence. 🙂 And true that I completely glossed over the "hangs on fetching" part. Morning coffee is now brewed.

**Comment by LoganWright** [comment] 2018-09-11 20:14
I'm going to close this since we're unable to reproduce it. If you're still having issues, reopen.

Thanks!

**Closed by LoganWright** 2018-09-11 20:14 UTC
