### ISSUE TITLE
204 response with compression enabled breaks some clients

### ISSUE THREAD

**Issue by grahamburgsma** [vapor/vapor#2464] opened 2020-08-07 13:45 UTC
A 204 response with compression enabled crashes some clients.

### Steps to reproduce

```swift
app.http.server.configuration.responseCompression = .enabled

app.get("test") { _ in HTTPStatus.noContent }
```

Use Postman to test the request, you will get an error `Error: Parse Error: Expected HTTP/`. On Android, using OkHttp, you will get a `EOFException`.

### Expected behavior

Doesn't crash clients. Looks like an issue that others have seen before as well: 

- https://github.com/influxdata/influxdb/issues/6624
- https://github.com/labstack/echo/issues/489

### Actual behavior

Crashes clients.

### Environment

Vapor 4.27.2

**Comment by tanner0101** [comment] 2020-08-07 15:39
@grahamburgsma thanks for reporting and for the links. Looks like the answer is here: https://github.com/labstack/echo/issues/489#issuecomment-217961984

```
   A server MUST NOT send a Transfer-Encoding header field in any
   response with a status code of 1xx (Informational) or 204 (No
   Content).  A server MUST NOT send a Transfer-Encoding header field in
   any 2xx (Successful) response to a CONNECT request (Section 4.3.6 of
   [RFC7231]).
```

**Comment by tanner0101** [comment] 2020-08-07 16:40
Looks like my previous comment is actually not the answer. The `Transfer-Encoding` header is different than the `Content-Encoding` header which is the issue here. (However, we should still strip the transfer encoding header). 

It looks like the RFC doesn't say anything about the `Content-Encoding` header needing to be stripped (https://tools.ietf.org/html/rfc7231#section-3.1.2.2). We should probably do it anyway though since this seems to be creating issues for clients. It also makes sense that if there is no content, there should be no content encoding.

**Comment by tanner0101** [comment] 2020-08-07 16:41
Related PR here: https://github.com/vapor/vapor/pull/2465. It looks like NIO's handlers are overriding my attempted fix here and still sending the header. I think I'll need to open a PR there.

**Comment by tanner0101** [comment] 2020-08-14 21:04
https://github.com/apple/swift-nio-extras/pull/105 was merged. Once tagged that will fix the problem 👍 

https://github.com/vapor/vapor/pull/2465 also adds a test to prevent regression. Thanks @grahamburgsma !

**Closed by tanner0101** 2020-08-14 21:04 UTC
Labels: bug
