### ISSUE TITLE
write failed: Broken pipe

### ISSUE THREAD

**Issue by sroebert** [vapor/vapor#736] opened 2016-12-02 11:07 UTC
Since the non-blocking server update (Vapor 1.2) I'm quite frequently getting the following message when trying to make an external HTTP request using the `drop.client`:

> An unhandled error occurred: send("write failed: Broken pipe")

The only thing that seems to solve it, is restarting the server.

**Comment by andreasley** [comment] 2016-12-02 12:47
So far, I've been unable to reproduce this. :(

- How many requests are you making?
- Are they GET or POST requests? 
- Do they run particularly long?
- How often is "quite frequently"? 
- Do some complete successfully?

> The only thing that seems to solve it, is restarting the server.

Does this imply that once requests start failing, all of them will fail all the time (until the server is restarted)?

**Comment by sroebert** [comment] 2016-12-02 13:30
It concerns both GET and POST requests and mainly while debugging the requests. So it might have to do something with leaving the request open for a longer time. If I find the time I'll try to come up with a way of reproducing it.

**Comment by andreasley** [comment] 2016-12-02 13:54
That could explain it. If you are pausing the process after a TCP connection has been established, the remote host might think that the connection is dead and closes its socket. When your process resumes, it attempts to send data and only then realizes that the TCP connection has been severed (hence the "broken pipe" error you're seeing). However, this shouldn't affect any future requests, because they open new connections.

**Comment by sroebert** [comment] 2016-12-02 14:37
Once I got into that state, no calls would work anymore. I'll play around a bit too see if I can find a pattern.

**Comment by sroebert** [comment] 2016-12-03 09:03
Ok, I reverted back to Vapor 1.1.13 and it also seems to have this problem. It seems to be happening after a certain amount of time after I used the `drop.client`, so I am guessing when the socket for the first connection was closed.

**Comment by andreasley** [comment] 2016-12-03 09:10
If you'd be willing to share the code you're using, I'd gladly take a closer look.

**Comment by sroebert** [comment] 2016-12-03 09:11
Thanks, but I figured it out I guess. But now I am wondering if I am using the `Client` in a wrong way. The `Client` sets up a stream once, once the stream gets closed, it will not automatically create a new one. If I would create a new client it would work, but I guess it would be nicer if the `Client` simply opens a new stream.

**Comment by andreasley** [comment] 2016-12-03 09:25
Every `get` or `post` on a `drop.client` opens a new connection, so something is definitely wrong. However, I can't seem to reproduce the issue.

**Comment by sroebert** [comment] 2016-12-03 09:32
As far as I can see, when creating a client, it creates a connection and the connection is reused. I am keeping the client and reuse it. I just wrote a small piece of code to create a new connection and this seems to solve my problem. I'll create a pull request to show what I mean.

**Comment by sroebert** [comment] 2016-12-03 10:18
Ok, as it is in engine, the pull request is there: vapor/engine#79

**Comment by tannernelson** [comment] 2016-12-15 16:47
Closing this since vapor/engine#79 was also closed. Creating an engine client is meant for sending rapid request/response over a single open connection.

If you want to create a new connection each time, use the static methods instead.

**Closed by tannernelson** 2016-12-15 16:47 UTC
