### ISSUE TITLE
Non deterministic TSan error when running vapor tests

### ISSUE THREAD

**Issue by Davidde94** [vapor/vapor#2612] opened 2021-04-27 15:55 UTC
Error occurs when running tests with TSan in debug mode, Ubuntu 20.04, Swift 5.4.

Test Case 'WebSocketTests.testWebSocketClient' started at 2021-04-27 15:26:43.625
[ INFO ] GET /ws [request-id: F825C823-35B3-4E22-B2F8-414D80E2DBA8]
[ WARNING ] read(descriptor:pointer:size:): Connection reset by peer (errno: 104) [request-id: F825C823-35B3-4E22-B2F8-414D80E2DBA8]
/workspace/.logs/**/*.log/54AE24E8-B865-4DB9-81ED-7CB933E0417D/repos/vapor/Tests/VaporTests/WebSocketTests.swift:10: Fatal error: leaking promise created at (file: "/workspace/.logs/**/*.log/54AE24E8-B865-4DB9-81ED-7CB933E0417D/repos/vapor/Tests/VaporTests/WebSocketTests.swift", line: 10)
Current stack trace:
0    libswiftCore.so                    0x00007fa8e8b44210 swift_reportError + 50
1    libswiftCore.so                    0x00007fa8e8bb8fc0 _swift_stdlib_reportFatalErrorInFile + 112
2    libswiftCore.so                    0x00007fa8e88a1c40 _assertionFailure(_:_:file:line:flags:) + 1329
3    vaporPackageTests.xctest           0x000055d9cf819512 <unavailable> + 12018962
4    vaporPackageTests.xctest           0x000055d9cf824f8e <unavailable> + 12066702
5    vaporPackageTests.xctest           0x000055d9cf977e67 <unavailable> + 13454951
6    vaporPackageTests.xctest           0x000055d9cf977d82 <unavailable> + 13454722
7    vaporPackageTests.xctest           0x000055d9cf818cb5 <unavailable> + 12016821
8    vaporPackageTests.xctest           0x000055d9cf8197ef <unavailable> + 12019695
9    libswiftCore.so                    0x00007fa8e8b467eb <unavailable> + 4192235
10   vaporPackageTests.xctest           0x000055d9d0315b12 <unavailable> + 23538450
11   libswiftCore.so                    0x00007fa8e8b467eb <unavailable> + 4192235
12   vaporPackageTests.xctest           0x000055d9cfde5bbf <unavailable> + 18099135
13   vaporPackageTests.xctest           0x000055d9cfde5c14 <unavailable> + 18099220
14   libswiftCore.so                    0x00007fa8e8b467eb <unavailable> + 4192235
15   libswiftCore.so                    0x00007fa8e8b3d030 swift_arrayDestroy + 59
16   libswiftCore.so                    0x00007fa8e88eedc0 _ContiguousArrayStorage.__deallocating_deinit + 36
0x55d9cef560bd, closure #1 (Swift.Int32) -> () in static Backtrace.Backtrace.install() -> () at /workspace/.logs/**/*.log/54AE24E8-B865-4DB9-81ED-7CB933E0417D/repos/vapor/.build/checkouts/swift-backtrace/Sources/Backtrace/Backtrace.swift:67
0x55d9cef560fe, @objc closure #1 (Swift.Int32) -> () in static Backtrace.Backtrace.install() -> () at /workspace/.logs/**/*.log/54AE24E8-B865-4DB9-81ED-7CB933E0417D/repos/vapor/<compiler-generated>:0
0x55d9cee0cf86, CallUserSignalHandler at /home/build-user/llvm-project/compiler-rt/lib/tsan/rtl/tsan_interceptors_posix.cpp:1924
0x55d9cee43a61, rtl_generic_sighandler at /home/build-user/llvm-project/compiler-rt/lib/tsan/rtl/tsan_interceptors_posix.cpp:2016
0x55d9cee43a61, rtl_sighandler at /home/build-user/llvm-project/compiler-rt/lib/tsan/rtl/tsan_interceptors_posix.cpp:2037
0x7fa8e87213bf
0x7fa8e88a2307
0x55d9cf819511, closure #1 () -> () in NIO.EventLoopFuture.deinit at /workspace/.logs/**/*.log/54AE24E8-B865-4DB9-81ED-7CB933E0417D/repos/swift-nio/Sources/NIO/EventLoopFuture.swift:423
0x55d9cf824f8d, partial apply forwarder for closure #1 () -> () in NIO.EventLoopFuture.deinit at /workspace/.logs/**/*.log/54AE24E8-B865-4DB9-81ED-7CB933E0417D/repos/vapor/<compiler-generated>:0
0x55d9cf977e66, closure #1 () -> Swift.Bool in implicit closure #1 () -> Swift.Bool in NIO.debugOnly(() -> ()) -> () at /workspace/.logs/**/*.log/54AE24E8-B865-4DB9-81ED-7CB933E0417D/repos/swift-nio/Sources/NIO/Utilities.swift:44
0x55d9cf977d81, NIO.debugOnly(() -> ()) -> () at /workspace/.logs/**/*.log/54AE24E8-B865-4DB9-81ED-7CB933E0417D/repos/swift-nio/Sources/NIO/Utilities.swift:44
0x55d9cf818cb4, NIO.EventLoopFuture.deinit at /workspace/.logs/**/*.log/54AE24E8-B865-4DB9-81ED-7CB933E0417D/repos/swift-nio/Sources/NIO/EventLoopFuture.swift:419
0x55d9cf8197ee, NIO.EventLoopFuture.__deallocating_deinit at /workspace/.logs/**/*.log/54AE24E8-B865-4DB9-81ED-7CB933E0417D/repos/swift-nio/Sources/NIO/EventLoopFuture.swift:0
0x7fa8e8b467ea
0x55d9d0315b11, objectdestroy.5 at /workspace/.logs/**/*.log/54AE24E8-B865-4DB9-81ED-7CB933E0417D/repos/vapor/<compiler-generated>:0
0x7fa8e8b467ea
0x55d9cfde5bbe, NIOWebSocket.NIOWebSocketClientUpgrader.deinit at /workspace/.logs/**/*.log/54AE24E8-B865-4DB9-81ED-7CB933E0417D/repos/swift-nio/Sources/NIOWebSocket/NIOWebSocketClientUpgrader.swift:0
0x55d9cfde5c13, NIOWebSocket.NIOWebSocketClientUpgrader.__deallocating_deinit at /workspace/.logs/**/*.log/54AE24E8-B865-4DB9-81ED-7CB933E0417D/repos/swift-nio/Sources/NIOWebSocket/NIOWebSocketClientUpgrader.swift:0
0x7fa8e8b467ea
0x7fa8e8b3d06a
0x7fa8e88eede3
Exited with signal code 4

**Comment by 0xTim** [comment] 2021-05-07 15:10
Closing as a duplicate of #2610

**Closed by 0xTim** 2021-05-07 15:10 UTC
Labels: bug
